### ISSUE TITLE
Doc: contents/touchpad-disable

### ISSUE THREAD

**Issue by carywreams** [system76/docs#1007]
## Request

consider updating [the article](https://support.system76.com/articles/touchpad-disable/) to alert readers to differences between xserver-xorg-input-libinput (not covered) and xserver-xorg-input-synaptics (whose syndaemon is current focus of article) and any nuances you wish to share regarding those differences.

According to this [article](https://wayland.freedesktop.org/libinput/doc/1.14.3/palm-detection.html#disable-while-typing), libinput does its own thing, disabling the touchpad while typing and is not configurable as is the -synaptics/syndaemon.

Potential Benefits of the change:

+ reduced confusion on the part of reader
+ reduced likelihood for casually installing -synaptics to gain access to syndaemon
+ reduced downstream confusion resulting from -libinput and -synaptics drivers co-existing

_also_, the [web page](https://support.system76.com/articles/touchpad-disable/) indicates a May 3, 2022 last update,  while this repo's activity for the page indicates a  Sep 30, 2021 last mod. Perhaps that's a build process result, but it originally left me with the impression that the article was current with respect to latest pop!_os. 

Thanks

**Comment by ahoneybun** [comment]
We have merged the two articles so I believe this has been fixed, if not please open a new issue!

**Comment by carywreams** [comment]
@ahoneybun - thanks.
