### ISSUE TITLE
unclear specific version reference in difference-between-pop-ubuntu

### ISSUE THREAD

**Issue by joyously** [system76/docs#1011]
At the bottom of docs/content/difference-between-pop-ubuntu.md it says
> Refresh Installs are only available on a fresh install of either Pop!_OS 19.04 or 18.04 (not through upgrading).

Is this a statement that needs to change to include recent versions, or is it only supported in those two versions?

**Comment by jacobgkau** [comment]
The recovery partition started being a feature with 18.04; you would still not have one if you installed 17.10 and kept the same install up-to-date until now.

Given the nature of this article (not really supporting any particular troubleshooting/etc), I would not be opposed to removing the sentence entirely. The recovery partition is also not available on legacy BIOS/CSM installs, or with most custom partition layouts, but we don't say anything about those cases here. (Also, a user should be able to perform a refresh install from a live disk even if they don't have a recovery partition.)

**Comment by leviport** [comment]
That's a good point as well. When we're updating this section, let's also add a link to the recovery partition article: https://support.system76.com/articles/pop-recovery

**Comment by ahoneybun** [comment]
We updated that article recently so let me know if it still is unclear in a new issue.
