### ISSUE TITLE
Docs on how to disable Intell Management Engine 

### ISSUE THREAD

**Issue by NukeManDan** [system76/docs#1023]
https://support.system76.com/articles/boot-menu

I understand that IME should be something that can be disabled: https://www.notebookcheck.net/System76-to-disable-Intel-Management-Engine-on-its-notebooks.267696.0.html

I cannot seem to see a way to do this in the docs.

**Comment by jacobgkau** [comment]
That third-party article from 2017 was written before System76 Open Firmware with Coreboot existed, and is referring to the proprietary firmware that older models shipped with.

For Open Firmware systems, the ME is typically disabled by default unless doing so would break functionality (such as suspend/resume). There is some information about manually disabling (or enabling) the ME here: https://github.com/system76/firmware-open/blob/master/docs/intel-me.md 

For proprietary firmware systems, if the option to disable (or enable) the ME is available, it is typically located under Advanced > Advanced Chipset Control. Again, it's usually disabled by default, although there have been some models that required re-disabling after an over-the-air firmware update; see this section of the firmware update instructions article: https://support.system76.com/articles/system-firmware#disabling-the-me 

If you own System76 hardware, feel free to reach out to the [support team](https://support.system76.com/) for information about the ME on your specific model; if you are considering System76 hardware, feel free to reach out to the [sales team](https://system76.com/contact).

**Comment by NukeManDan** [comment]
I am on a `gaze17-3060-b`  ended up using the firmware source to disable things. Thanks! I still would think this message above would make a solid docs article , perhaps with a bit more detials included :+1:
