### ISSUE TITLE
Docs on how to customize fan speed (Gazelle)

### ISSUE THREAD

**Issue by NukeManDan** [system76/docs#1024]
I have the 17" Gazelle with NVIDIA GeForce RTX 3060 and it's _SO LOUD_ when performing anything outside idle operations. 

I need a was to modify fan speed settings for a "quite mode" experience when needed - for calls and presentations specifcally

https://www.reddit.com/r/System76/comments/mqek0d/fan_control/  &&  https://github.com/system76/ec/pull/190 discusses that older models may have this, but there are no docs here on this or mention of fan control in general. I would like some :pray: 

This is not super `CLI n00b` friendly material: https://devimalplanet.com/guide-how-to-adjust-the-fan-curve-on-system76-laptops  - is there any way to tweak these settings outside of manually editing the firmware like this? Perhaps via a GUI?

I have used https://gitlab.com/leinardi/gwe that supports GPU fan speed control, but I have not tested here. I also need this for the system fans overall, so unclear if it would work

**Comment by ahoneybun** [comment]
The fan speeds on laptops are set in the firmware so to my knowledge making those changes in custom firmware is needed at this time.
