### ISSUE TITLE
E: Unable to locate package protonvpn

### ISSUE THREAD

**Issue by jpr42** [system76/docs#1033]
I'm trying to install the ProtonVPN GUI for my !Pop-OS computer. However, I am having problems.

Here are the instructions I used:
- https://support.system76.com/articles/use-vpn-software (System76)
- https://protonvpn.com/support/linux-ubuntu-vpn-setup/ (ProtonVPN)

I've installed the `.deb` package with `Eddy` and then I ran the following commands:

```
$ sudo apt update
Hit:1 http://apt.pop-os.org/proprietary jammy InRelease
Hit:2 http://apt.pop-os.org/release jammy InRelease
Hit:3 http://apt.pop-os.org/ubuntu jammy InRelease
Hit:4 http://apt.pop-os.org/ubuntu jammy-security InRelease
Hit:5 http://apt.pop-os.org/ubuntu jammy-updates InRelease
Hit:6 http://apt.pop-os.org/ubuntu jammy-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
$ sudo apt install protonvpn
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package protonvpn
```

However, I'm unable to install ProtonVPN. I just get the error:
```
E: Unable to locate package protonvpn
```

I'm unsure how to proceed from here.

**Comment by n3m0-22** [comment]
The `.deb` for ProtonVPN just adds the source. It looks like it was not added. I would recommend opening a terminal in the directory where the `protonvpn-stable-release_1.0.1-1_all.deb` file is, probably Downloads, and run the command `sudo dpkg -i protonvpn-stable-release_1.0.1-1_all.deb`. Then run `sudo apt update` again. In the output you should see a line like this.

`Hit:4 https://repo.protonvpn.com/debian stable InRelease`. 

Once you see that `sudo apt install protonvpn` should work.

**Comment by jpr42** [comment]
The `repo.protonvpn.com/debian` isn't getting added.

```
@pop-os:~/Downloads$ ls
protonvpn-stable-release_1.0.1-1_all.deb

@pop-os:~/Downloads$ sudo dpkg -i protonvpn-stable-release_1.0.1-1_all.deb 
(Reading database ... 342918 files and directories currently installed.)
Preparing to unpack protonvpn-stable-release_1.0.1-1_all.deb ...
Unpacking protonvpn-stable-release (1.0.1-1) over (1.0.1-1) ...
Setting up protonvpn-stable-release (1.0.1-1) ...

@pop-os:~/Downloads$ sudo apt update
Hit:1 http://apt.pop-os.org/proprietary jammy InRelease
Hit:2 http://apt.pop-os.org/release jammy InRelease
Hit:3 http://apt.pop-os.org/ubuntu jammy InRelease
Hit:4 http://apt.pop-os.org/ubuntu jammy-security InRelease
Hit:5 http://apt.pop-os.org/ubuntu jammy-updates InRelease
Hit:6 http://apt.pop-os.org/ubuntu jammy-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
```

**Comment by n3m0-22** [comment]
I see the issue. It's adding a key as well as the source. I was able reproduce what your are seeing. To fix it run the following.

Note:
When you run the 5th command you will be prompted to add the key.
```
Package to install ProtonVPN GPG key and stable repo
Do you want to install the software package? [y/N]:
```
You will need to answer `y`.

1. `sudo apt purge ~nprotonvpn`
2. `sudo apt autoremove`
3. `sudo apt update`
4. `sudo apt install gdebi`
5. `sudo gdebi protonvpn-stable-release_1.0.1-1_all.deb` 
6. `sudo apt update`

Assuming you are now seeing `repo.protonvpn.com/debian` you should be able to run `sudo apt install protonvpn`.

**Comment by jpr42** [comment]
That fixed the issue :D

**Comment by BJsB0T** [comment]
> I see the issue. It's adding a key as well as the source. I was able reproduce what your are seeing. To fix it run the following.
> 
> Note: When you run the 5th command you will be prompted to add the key. You will also need to run this command from the same directory as the `.deb` file.
> 
> ```
> Package to install ProtonVPN GPG key and stable repo
> Do you want to install the software package? [y/N]:
> ```
> 
> You will need to answer `y`.
> 
> 1. `sudo apt purge ~nprotonvpn`
> 2. `sudo apt autoremove`
> 3. `sudo apt update`
> 4. `sudo apt install gdebi`
> 5. `sudo gdebi protonvpn-stable-release_1.0.1-1_all.deb`
> 6. `sudo apt update`
> 7. `sudo apt install gnome-shell-extension-appindicator gir1.2-appindicator3-0.1`
> 
> Assuming you are now seeing `repo.protonvpn.com/debian` you should be able to run `sudo apt install protonvpn`.

I've followed all these steps but sadly still not working! 
![ERROR](https://github.com/system76/docs/assets/153606242/64cfb38a-c675-4f44-90cd-5d1c5cfcab8c)

**Comment by ahoneybun** [comment]
@BJsB0T generally that is a network issue so they might had issues at that time. I just installed the .deb for their stable release with Eddy on Pop 22.04 and it worked fine.

**Comment by BJsB0T** [comment]
> @BJsB0T generally that is a network issue so they might had issues at that time. I just installed the .deb for their stable release with Eddy on Pop 22.04 and it worked fine.

Yeah maybe! So maybe I should wait for a couple of days and try again and see!
