### ISSUE TITLE
Not quite an "issue" but a thing to be aware of for cuda / tensorflow etc

### ISSUE THREAD

**Issue by BStudent** [system76/docs#105]
First, congrats on this awesome feature.   
I posted a screenshot earlier of CUDA samples running on my oryxp4 after simply installing PoP clean and following the instructions on this page.  
And that was a result of building all of the NVIDIA samples - a great way to assure that everything works.
*Most* people will not build those samples - they will load their CUDA + Tensorflow of choice using the alternative mechanism and start programming away in Python.
The thing I noticed is that if you try and build the samples in 9.1 or 9.0 instead of 9.2, the make / compile process will barf because most of the demo programs are written in C++, and there was a jump in gcc versions from 9.1 to 9.2 (which makes 9.2 compatible with gcc  in PopOS/bionic 18.04).  Of course your gcc toolchain can be controlled by the same alternatives mechanism described for CUDA / Tensorflow.  If one wanted to be super anal about it, one could offer an option to switch the toolchain as well as the CUDA libs - but the toolchain swap could have side effects on other programs that depend on gcc. 
My guess is that the person writing CUDA/Tensorflow in C++ is sophisticated enough to understand that error when they see it, and run the alternatives procedure for gcc separately.   And they are comparatively rare among users.
Meanwhile, I am pretty sure the python-based programmer, comprising 98% of use cases, won't know the difference.
So, probably no action required - I think it likely that offering to swap gcc toolchain versions would  cause more support incidents than it would prevent.  
But I did at least want to point it out in case it ever comes up.

**Comment by ahoneybun** [comment]
I think you mean this command to switch between GCC versions?:

sudo update-alternatives –config

I've thought about adding that to this page:

https://support.system76.com/articles/use-tensorflow/

**Comment by kylerchin** [comment]
Thanks! Was having this problem today, about to leave the same issue.

**Comment by ChiefHart** [comment]
> With Full Disk Encryption more then one password

Editorial correction: Sixth word "then" should be "than"

**Comment by ahoneybun** [comment]
Are you talking about a certain article? If so is this the password article?
