### ISSUE TITLE
No gear icon to access Repoman

### ISSUE THREAD

**Issue by curtsheller** [system76/docs#1058]
No gear icon to access Repoman from Pop_shop per docs: https://support.system76.com/articles/manage-repos-pop

Using Pop!_OS 22.04 LTS x86_64

**Comment by n3m0-22** [comment]
I can confirm this. The documentation will need to be updated for the new menu icon as well as `Ctrl` + `S`.

**Comment by leviport** [comment]
Ah yes, that changed recently, thanks for the report!

@Ampersandstorm could you put this on your list?
