### ISSUE TITLE
https://support.system76.com/articles/install-in-vm/ instructions are wrong (later stuck due to disk size)

### ISSUE THREAD

**Issue by matkoniecz** [system76/docs#1079]
https://support.system76.com/articles/install-in-vm/ claims

> Feel free to just pick the defaults here and click on the "Create" button.

This results in mysterious 

![screen03](https://user-images.githubusercontent.com/899988/199935203-93e19d29-a951-4309-997d-ef193ef22a9f.png)

(hovering over it results in displaying "Disk does not meet the minimum requirement")

Note that it happens despite selecting dynamically allocated disk size.

migrated from https://github.com/pop-os/website/issues/73 based on https://github.com/pop-os/website/issues/73#issuecomment-1303764793

**Comment by leviport** [comment]
I'm still not entirely convinced that the instructions are wrong. You've omitted the first part of the sentence that says, "After adjusting storage." It might be a little unclear what that means, but the preceding sentence is the one that tells the user how much space to allocate to the VM.
![s](https://user-images.githubusercontent.com/13512097/200025819-d5d0f84e-d9bf-40ba-8d57-f49861c1ccb5.png)

**Comment by matkoniecz** [comment]
note that section

> 7. Name Drive File and Confirm Size

where you can adjust size claims

> Feel free to just pick the defaults here and click on the "Create" button.
