### ISSUE TITLE
Last edited on date is inaccurate

### ISSUE THREAD

**Issue by fulldecent** [system76/docs#1100]
The first page links to the second evidence

<img width="1459" alt="Screenshot 2023-01-27 at 14 49 26" src="https://user-images.githubusercontent.com/382183/215184105-d11cf444-9c51-42a0-895c-23529c7f6a2f.png">
<img width="1459" alt="Screenshot 2023-01-27 at 14 49 31" src="https://user-images.githubusercontent.com/382183/215184113-8fd6eadd-ab0f-4189-978e-fe613984e4b5.png">

**Comment by leviport** [comment]
Huh, it looks like that date gets updated whenever any changes happen in any of the articles. The current date lines up with https://github.com/system76/docs/pull/1099
