### ISSUE TITLE
Add documentation on how to use ROCM on System76

### ISSUE THREAD

**Issue by guilt** [system76/docs#1110]
For those with somewhat recent AMD graphics cards, they should be able to run ROCM via Docker easily.

I was asked to add this to the support docs, so I am going to start by adding this ticket here.

I have already added the basic steps/scripts in [this gist](https://gist.github.com/guilt/6c901f7ac0a726685b6334798da77c00) but I am looking for more volunteers to test it. In the meantime, let me try to come up with better documentation that could be added to the portal. Even though I suck at it.

**Comment by jessecambon** [comment]
I am looking to test this and added a comment to the gist.

**Comment by jacobgkau** [comment]
We have instructions for installing ROCm now: https://support.system76.com/articles/rocm 

This was added in https://github.com/system76/docs/pull/1231 in April of this year. I'm closing this issue as being resolved by that PR.

**Comment by fruffy** [comment]
Running cosmic with 
```bash
OS: Pop!_OS 24.04 LTS x86_64
Kernel: 6.12.10-76061203-generic
DE: COSMIC
Theme: Pop-dark [GTK3]
Icons: Pop [GTK3]
Terminal: cosmic-term
CPU: AMD Ryzen AI 9 HX 370 w/ Radeon 890M (24) @ 4.367GHz
GPU: AMD ATI Radeon 880M / 890M

```

I am seeing the following error trying to install rocm. Is that a known problem? 
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hipsolver : Depends: libcholmod3 but it is not installable
             Depends: libsuitesparseconfig5 but it is not installable
 rocm-gdb : Depends: libtinfo5 but it is not installable
            Depends: libncurses5 but it is not installable
            Depends: libpython3.10 but it is not installable or
                     libpython3.8 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Possible that the package sources do not quite match?

**Comment by ahoneybun** [comment]
@fruffy these steps are for 22.04 while you are on 24.04 which can effect the steps. Since Pop 24.04 is still in Alpha these steps have not been updated for that release.
