### ISSUE TITLE
Repair the Bootloader fails: Unmet dependencies.

### ISSUE THREAD

**Issue by texttheater** [system76/docs#1146]
I followed the instructions on https://support.system76.com/articles/bootloader/ (Pop_OS!, EFI mode, NVMe drive). It works fine until I get to the part where it tells me to execute this command:

```
apt install --reinstall linux-image-generic linux-headers-generic
```

This fails with the following message:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 linux-generic : Depends: linux-image-generic (= 6.2.6.76060206.202303130630~1683753207~22.04~77c1465) but 6.2.6.76060206.202303130630~1685473338~22.04~995127e is to be installed
                 Depends: linux-headers-generic (= 6.2.6.76060206.202303130630~1683753207~22.04~77c1465) but 6.2.6.76060206.202303130630~1685473338~22.04~995127e is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by jacobgkau** [comment]
Does running the commands in the Package Manager Issues support article help? https://support.system76.com/articles/package-manager-pop 

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by jacobgkau** [comment]
Closing this issue since we didn't hear back. If you still need assistance, please see the links in the footer of my last message, or comment here again if you think it's an issue with the docs.
