### ISSUE TITLE
desktop-environment ubuntu-desktop bug (unmet dependencies)

### ISSUE THREAD

**Issue by keen101** [system76/docs#1151]
The system76 support article does not work for installing the ubuntu-desktop. (https://support.system76.com/articles/desktop-environment) 

$ sudo apt install ubuntu-desktop

The following packages have unmet dependencies:
 gnome-shell-extension-cosmic-dock : Breaks: gnome-shell-extension-ubuntu-dock but 72~ubuntu5.22.04.2.1 is to be installed
 ubuntu-desktop : Depends: pulseaudio
                  Recommends: pulseaudio-module-bluetooth but it is not going to be installed
 ubuntu-desktop-minimal : Depends: pulseaudio
                          Recommends: pulseaudio-module-bluetooth but it is not going to be installed
 update-manager : Depends: update-manager-core (= 1:22.04.10) but 1.0.0~1666200735~22.04~e720c01 is to be installed
                  Breaks: update-notifier (< 3.177)
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by leviport** [comment]
![2023-07-03_09-02-49](https://github.com/system76/docs/assets/13512097/9ee9a3dd-bfe1-4fa6-b1f5-4af596f3d998)

The article says to install `pop-desktop` on Pop!\_OS, and `ubuntu-desktop` on Ubuntu. That output indicates you're most likely installing `ubuntu-desktop` on Pop!\_OS, which would cause problems.
