### ISSUE TITLE
Repair GRUB after installing Windows 10 on Oryx Pro with existed Ubuntu 18.04

### ISSUE THREAD

**Issue by drNoob13** [system76/docs#116]
Hi,

I was trying to install Windows 10 on an existing Ubuntu 18.04 that shipped with Oryx Pro.

I follow the below instruction to repair Grub so that Ubuntu can be booted as an option with the newly installed Windows OS. 

Git:
      docs/_articles/grub.md

  https://support.system76.com/articles/grub/  

I found out that there is an additional command that needs to be executed to config the grub:

Before:
```
$...
$ apt install --reinstall grub-efi-amd64 linux-generic linux-headers-generic

```
After:
```
$...
$ apt install --reinstall grub-efi-amd64 linux-generic linux-headers-generic
$ update-grub

```
With that additional updating, GRUB is properly updated, and after a reboot, the system recognizes both OSes.

**Comment by ahoneybun** [comment]
Fixed with this commit:

https://github.com/system76/docs/commit/67318802451e467de2eb225ccf2ee00edb52fed5
