### ISSUE TITLE
Pop Shell on NixOS

### ISSUE THREAD

**Issue by syswraith** [system76/docs#1218]
https://support.system76.com/articles/pop-shell/
Can we add build instructions for using the Pop Shell on NixOS in this article?

https://github.com/pop-os/shell/issues/1700 (Thanks to @leviport for pointing me here)

**Comment by ahoneybun** [comment]
Building or adding it to NixOS? I would use the packaged version in nixpkgs:

https://search.nixos.org/packages?channel=23.11&show=gnomeExtensions.pop-shell&from=0&size=50&sort=relevance&type=packages&query=pop-shell

**Comment by syswraith** [comment]
> Building or adding it to NixOS? I would use the packaged version in nixpkgs:
> 
> https://search.nixos.org/packages?channel=23.11&show=gnomeExtensions.pop-shell&from=0&size=50&sort=relevance&type=packages&query=pop-shell

Will check it out and close the issue :+1:
