### ISSUE TITLE
blender and gpu rendering

### ISSUE THREAD

**Issue by kaydeejay** [system76/docs#1220]
Hello! Question about blender and gpu drivers.

I have been using blender as a video editor for a few years now, but it has always rendered very slowly. I worry that I've tried to install a few too many drivers and something has gotten mixed up at some point.

For unrelated reasons, I'm about to do an OS re-install so I will have a clean Pop!_os installation with the default video drivers (mesa, if I'm not mistaken). I'd like to know which additional video card drivers, if any, I should install in order to take advantage of blender gpu cycles rendering.

I asked this question elsewhere and was told that I should just install the open source amdgpu drivers, and that those will be compatible with blender. I'm unsure though because

1. I know that blender < 3.0 uses openCL for cycles rendering, and that this is no longer the case as of blender >= 3.0.
2. I believe blender >= 3.0 uses HIP instead, and this is not compatible with my gpu chipset (Radeon RX 5600).
3. I don't know that the amdgpu open source drivers contain either of these.

Advise appreciated!

**Comment by ahoneybun** [comment]
This is a bit outside of current docs scope but this is the breakdown:

For NVIDIA cards make sure that our system76-driver-nvidia package is installed or NVIDIA in-general on other OSes.
For AMD the amdgpu driver is in the kernel unless you need the Pro version which does not work with our newer kernels.

**Comment by jacobgkau** [comment]
Blender GPU rendering on AMD requires HIP. That can be added by installing amdgpu-pro or ROCm. On Pop!_OS, you're going to want to use ROCm. It hooks into the driver present in the default Pop!_OS kernel, and just adds the compute libraries on top.

Here are the commands to install ROCm on a default Pop!_OS installation (I just tested this on an AMD graphics system and confirmed it works with the Blender flatpak):

```
wget https://repo.radeon.com/rocm/rocm.gpg.key -O - | gpg --dearmor | sudo tee /etc/apt/keyrings/rocm.gpg > /dev/null
echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/6.1 jammy main" | sudo tee --append /etc/apt/sources.list.d/rocm.list
echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/rocm-pin-600
sudo apt update
sudo apt install rocm
```

After that, reboot for good measure, and then you'll want to download Blender directly from blender.org-- the packages in the Pop!_Shop have issues with GPU rendering (the .deb from Ubuntu doesn't have HIP support compiled in, and the Flatpak has sandboxing that prevents the GPU from being detected).

On a side note, if AMD doesn't support HIP on your card, then GPU rendering simply won't work on current versions of Blender. However, my Vega cards (which are several years older than your RX 5600) eventually got HIP support in the drivers after several years of waiting, so I'd expect your RX 5600 to support HIP by now, too.
