### ISSUE TITLE
Search errors

### ISSUE THREAD

**Issue by nobrowser** [system76/docs#1226]
Hi,

as of yesterday I cannot use the search function on the support page. As soon as I type anything in the entry box, I see an error message about malformed JSON or something (I can be persuaded to capture the exact message if needed). Looks like the kind of problem that happens when a site is tested against Chrome but not against Firefox.

I did try to purge my cache and local storage, to no effect.

Using Firefox 124.0.1 as packaged by PopOS.

I also wonder if this has anything to do with my seeming inability to create a support ticket. When I called over the phone last week Stetson created a ticket for me and then I could communicate with the team over email as usual. But me creating a ticket through the website still doesn't work, apparently.

-- 
Ian

**Comment by leviport** [comment]
Can confirm, search is broken. As a workaround, Ctrl + F to find on page might be sufficient.

>I also wonder if this has anything to do with my seeming inability to create a support ticket. 

Probably not. Those are two very separate and different software stacks.

**Comment by ahoneybun** [comment]
This should be fixed.

**Comment by leviport** [comment]
Confirmed
