### ISSUE TITLE
Explain how to install Popsicle if you AREN'T running Pop!_OS

### ISSUE THREAD

**Issue by dandv** [system76/docs#125]
https://support.system76.com/articles/pop-live-disk/ says

> You can run a full version of Pop!_OS from a USB drive (often known as a thumb drive, flash drive, or USB stick) in what’s known as a live environment. Using a live environment (live disk) is useful for:
>
> * Installing Pop!_OS
> [...]
> 
> we’ll use Popsicle.
> 
> Popsicle is an open source app for Linux that allows you to “burn images to USB drives safely and easily”

Then it continues / runs on ;) with:

>, it is installed in Pop!_OS 18.04 and up. If you are running Pop!_OS 17.10 you can install it like so in a terminal:

It's great that Popsicle is installed in Pop!_OS, but if the readers of this page want *to* install Pop_OS!, these instructions won't help them.

Not sure what the target audience of this page is, but if it's prospective Pop!_OS users, Popsicle installation instructions for them would be useful.

**Comment by mmstick** [comment]
You're referencing the article titled "Create and Use Bootable Media **on Pop!_OS**". You're asking for ["Create and Use Bootable Media from Other OS's"](https://support.system76.com/articles/live-disk/), which already exists.

**Comment by dandv** [comment]
The problem with that other article is https://github.com/pop-os/docs/issues/63

**Comment by mmstick** [comment]
A little confused. What's the problem? Etcher will work for everyone that's not already on Pop OS. If you're on Pop OS, then Popsicle is the preferred tool to use. Popsicle isn't available outside of Pop OS, unless you're willing to build it from source with Cargo. I wouldn't be surprised if some distributions have already packaged it though, like Arch.

**Comment by dandv** [comment]
The problem with Etcher is that the image I flashed won't boot (see the issue I liked to above). Does Pop OS absolutely need something that prevents the good old Startup Disc Creator from flashing its image?

**Comment by ahoneybun** [comment]
I've seen issues with Startup Disc Creator so I recommend Etcher/Popsicle.
