### ISSUE TITLE
feat cosmic in desktop-environment

### ISSUE THREAD

**Issue by Malix-Labs** [system76/docs#1257]
COSMIC is missing in : https://github.com/system76/docs/blob/master/content/desktop-environment.md

Also, it isn't clear if / when it will be the default (and when GNOME Shell wouldn't be anymore)

**Comment by ahoneybun** [comment]
COSMIC will be the default for Pop!_OS 24.04 and currently is an Alpha so there is no reason to have it in this article currently.
