### ISSUE TITLE
Key Icon does not show up on keyboard

### ISSUE THREAD

**Issue by echeadle** [system76/docs#155]
"Press the|  <Key Icon 1> / <Key Icon 2>  | key then type 'disks' to launch the Disks application."

On my Darter Pro the "key icon 2"  is not there.  Key Icon 1 is right of the fn key.  The other icon looks like the Ubuntu logo.  I don't see it anywhere.  

It may be obvious to people who use Ubuntu all of the time, but this is my first ubuntu laptop so I am just learning.  You might either have an alternative way to open the disks app and/or make sure the people understand what model(s) on which the key is found.

**Comment by ahoneybun** [comment]
What article are you referring to? We don't have any article that uses key icon 1 and key icon 2 as ways to describe the Ubuntu/Pop key.

**Comment by echeadle** [comment]
Sorry about that. On the web page: https://support.system76.com/articles/live-disk/
you have the line: "Press the|  /   key then type 'disks' to launch the Disks application."
It has two icons of keys on either side of the "/"  slant line.
Since you can't see the icons on the github site nor can I add them to this description, I used the <key icon 1>  as a placeholder for what you can't see in github or in this text box.  If you look at the web page and find the line, the second icon looks like a key that the ubuntu logo on it. My darter pro does not have that key.   On another page I saw an key icon that had 4 different symbols.  One of the four is on my keyboard and it works like the description says.

This is my first system76 machine and I did not know that key was different on different machines.  Now I do.  So I was thinking for beginners it might be better to have the icon that has four images on it, or a description that says the key may look like  ....

**Comment by ahoneybun** [comment]
Our website renders those icons as the Pop key and the Ubuntu key. Your Darter Pro would have the Pop key to the right of the Fn key and to the left of the Alt key:

https://d1vhcvzji58n1j.cloudfront.net/assets/products/darp5/guide/top-5107b4871c.jpg
