### ISSUE TITLE
Cuda Install Instuctions issue

### ISSUE THREAD

**Issue by CaptKrasno** [system76/docs#156]
I just attempted to install cuda using the instructions on this article: https://github.com/system76/docs/blob/gh-pages/_articles/cuda.md  

Cuda was installed successfully but there were some issues:
1:  When installed according to these instructions cuda is not found by default within cmake ( I had to set CUDA_TOOLKIT_ROOT_DIR to "/usr/lib/cuda")

2: Cuda executables are not runnable from Everywhere.  for example running  "nvcc -V" fails but "/usr/lib/cuda/bin/nvcc -V" runs fine

**Comment by mmstick** [comment]
You should restart your system after installing the toolkit

**Comment by CaptKrasno** [comment]
thanks,   that did the trick.
