### ISSUE TITLE
No manual for Serval WS?

### ISSUE THREAD

**Issue by JoeOsborn** [system76/docs#164]
The manuals page does not list any instructions, maintenance, or repair information for the Serval WS.

**Comment by ahoneybun** [comment]
A service manual doesn't exist at this time.

**Comment by JoeOsborn** [comment]
In the meantime is there an alternative like a teardown/reassemble video, schematics/diagrams, or something?  Even a link to an end user resource could be useful.

**Comment by ahoneybun** [comment]
@JoeOsborn the service manual is now up:

https://github.com/system76/docs/commit/f3ec5765dae60b1a937bd28f4862240b0c1ed768
