### ISSUE TITLE
`Repair the bootloader` page begins with incorrect information.

### ISSUE THREAD

**Issue by brs17** [system76/docs#169]
The `Repair the bootloader` [page](https://support.system76.com/articles/bootloader/) begins with the following paragraph.

 `GRUB is the bootloader. It takes care of getting the operating system started up. It is also responsible for allowing the user to select between multiple operating systems at boot. Sometimes, GRUB can break, and it may not let you boot into your computer to fix the problem.`

On Pop!_OS machines, GRUB is not the default boot-loader (in most cases).  This paragraph/document potentially should be reorganized to mention the bootloader that comes on our current machines first (systemd-boot). It potentially should also be done for the fact that it is linked to from Pop!_OS related documentation (https://pop.system76.com/docs/pop-live-disk/, https://support.system76.com/articles/pop-live-disk/)

Thoughts @ahoneybun ?

**Comment by ahoneybun** [comment]
Fixed : 2865d826394dd2dd86dbc27c9973773b43c1a545
