### ISSUE TITLE
Steam installation?

### ISSUE THREAD

**Issue by ryanleesipes** [system76/docs#19]
Can someone check to make sure you can still install Steam without issue from the normal repo? I believe I had to enable to multiverse last time (for 32-bit support).

**Comment by Xeboc** [comment]
It installs ok with the default settings.  Multiverse is enabled by default.

**Comment by ryanleesipes** [comment]
@Xeboc did you install through the CLI? Or through the App Center?

**Comment by Xeboc** [comment]
CLI.  And you are correct that it's not showing up in the app center at all.  I've hidden the article pending a rewrite.  The app center is getting worse.....

**Comment by ryanleesipes** [comment]
@Xeboc friggin' app center. Maybe I should just write my own. :smile:

**Comment by ahoneybun** [comment]
mm that's really weird, I remember having an issue on Kubuntu that we could not even find it with 'apt search'

**Comment by Xeboc** [comment]
The new app center removed all of the CLI commands also, and just isn't that awesome anymore....  We are hoping that it gets improved soon.  We just need to have both the CLI and the software center info in the article, with a note to use whatever works.

**Comment by ahoneybun** [comment]
adding a tutorial to install with the CLI, just trying to fix a broken image link before sending a PR.

**Comment by ryanleesipes** [comment]
Someone want to pop this problem upstream? So that our friends at Canonical know?

**Comment by ahoneybun** [comment]
I just confirmed that it is not showing up in a clean installed VM from the App Center. I'll look to see if there is a bug.

**Comment by Xeboc** [comment]
Thank you for that.  There's quite a bit broken about the App Center right now.  Steam isn't the only one not to be found....

**Comment by ahoneybun** [comment]
I use apt mostly for installing things but I can understand how GNOME Software needs to be improved. Hopefully fixing Steam can help with finding other applications missing.

**Comment by ahoneybun** [comment]
With this commit: https://github.com/system76/docs/commit/e0f1be814e3168d54047b6873b884a1d6e859895

Should this issue be closed then?

**Comment by Xeboc** [comment]
Agreed.  Thank you for the complete article.  👍
