### ISSUE TITLE
desktop-environment seems to be outdated for 19.10

### ISSUE THREAD

**Issue by konsumer** [system76/docs#222]
[article](https://support.system76.com/articles/desktop-environment/) has instructions for using `lightdm` to manage desktop session, but I don't have that installed on 19.10 (looks like I am running `gdm3`)

**Comment by mmstick** [comment]
It's not necessary in 18.04 or 19.10, since GDM is also suitable as a display manager for choosing between multiple desktop sessions.

**Comment by konsumer** [comment]
I just mean things like this don't apply on my system:

> `sudo dpkg-reconfigure lightdm`

and gdm3 uses different method for setting the default desktop, not

> `sudo gedit /etc/lightdm/lightdm.conf`

**Comment by ahoneybun** [comment]
The reconfigure command is listed for Ubuntu 16.04 so it is still related and up to date though the lightdm.conf could be update since that would only be for 16.04 as well. Which section of the article are you talking about in this case?

**Comment by konsumer** [comment]
@ahoneybun It's the first command listed on the linked article. I see that 16.04 is called out specifically, but I couldn't see how to do the same thing on 19.10.

I am not using Pop!OS anymore (moved to manjaro) so this is really just a report of a gap in docs. if it doesn't apply, feel free to ignore.
