### ISSUE TITLE
Switching to Ubuntu From Apple: Working With Images

### ISSUE THREAD

**Issue by yhoiseth** [system76/docs#226]
I checked out [Switching to Ubuntu From Apple](https://support.system76.com/articles/switch/) because I'm curious about how I can manage my photos if I switch. I currently use Apple Photos for this, and it syncs with my iPhone using iCloud.

However, under the heading _Working With Images_, photo management isn't mentioned. Instead, image manipulation is:

> Ubuntu has several powerful image manipulation programs. Gimp, darktable, and Inkscape will do what Adobe products can. Plus, they are free, which is a huge bonus. Adobe products don’t currently run on Ubuntu, but there are plenty of replacement software options.

I understand that this is relevant for advanced users, but it would be interesting for me (as a less advanced user) to get some guidance on how I can replace Apple Photos. 

Just to be clear, I don't know if any good options exist. iCloud.com works to some extent, but seems to lack a lot of features.

**Comment by ahoneybun** [comment]
For photo management you have quite a few tools like digiKam, Shotwell and F-Spot.

**Comment by yhoiseth** [comment]
@ahoneybun I'm not sure if I agree that this issue should be closed. Photo management seems to me like an essential thing to include in this switching guide. Just my two cents 🙂
