### ISSUE TITLE
Privacy policy does not reflect extent of Google tracking

### ISSUE THREAD

**Issue by benlowry** [system76/docs#228]
This documentation seems to be not-hosted on Github, the reason I am posting is it does not disclose all logins and registrations being tracked by Google.  In fact it is quite hard to contact system76 at all without registering and disclosing your usage to Google, which you don't disclose to your users.  Writing directly to email addresses just bounces so it's unnecessarily difficult too.

https://system76.com/privacy

**Comment by benlowry** [comment]
Twitter, New Relic, Facebook and a mapping service from Google are also undisclosed companions on some or all page views.

**Comment by btkostner** [comment]
Hello Ben,

What email address did you try emailing, and where did you find it? I'll try to get that fixed.

As for the login page. There are two services that load. One of them is Google analytics (which is disclosed), and the second is a third party sales chat widget that might show.

The Twitter, New Relic, and Facebook code is used on an old legacy system that, aside from a couple of pages, should not be visible.

I'll take time today to try and remove the social trackers and New Relic from our old code base. Any needed updates to the privacy page should also be happening soon.

**Comment by ahoneybun** [comment]
@btkostner did those privacy page updates happen so that I can close this issue?

**Comment by joemcl** [comment]
@ahoneybun it looks like your concerns were addressed. The only 'tracker' that Privacy Badger shows now at https://system76.com is Google Analytics. https://system76.com/privacy discloses the use of Google Analytics as well as Quantcast Analytics. cc: @btkostner .

**Comment by Oymate** [comment]
@ahoneybun Everything seems to be addressed, I think it's clear for closing.
