### ISSUE TITLE
Include link in Header back to Support Home

### ISSUE THREAD

**Issue by ryanleesipes** [system76/docs#23]
Currently when reading a support doc, there is no button to press to get back to the main support page. We should include that on each page somewhere in the blue header (or if there is a better place I will rely on @cassidyjames design kung-fu to decide on that).

**Comment by WatchMkr** [comment]
While not very intuitive, it's the support icon. This will be wrapped into the support page/docs projects.

**Comment by ryanleesipes** [comment]
@WatchMkr "WatchMkr" eh. Fancy username there.
