### ISSUE TITLE
galp4 manual states that M.2 Interface supports PCIe gen4

### ISSUE THREAD

**Issue by mokus0** [system76/docs#249]
While this is possible, the CPU does not support it so it seems unlikely. Does this system mainboard have a PCIe switch that aggregates the gen3 lanes from the cpu, or is that detail in the doc a typo?

**Comment by brs17** [comment]
I do believe this is a typo that should say instead, PCIe x4. @thomas-zimmerman / @ahoneybun can confirm this.

**Comment by mokus0** [comment]
I've obtained the schematic and checked it, it is indeed a typo and PCIe gen3 x4 would be the correct claim

**Comment by ahoneybun** [comment]
Fixed in https://github.com/system76/docs/pull/252
