### ISSUE TITLE
Updating Cuda version to 10.0 ?

### ISSUE THREAD

**Issue by 1412kauti** [system76/docs#251]
I've been using the tensorflow-cuda-latest for quite some time now but its still in 9.2 which is depreciated for certain frameworks(NVIDIA RAPIDS, which clearly shows that). Will there be an update to 10.0 ? or do I have to do it manually?

**Comment by ahoneybun** [comment]
This package has been updated to 10.0 and on the way to be updated to 10.2 at this time.
