### ISSUE TITLE
Copyright in footer does not show copyright of current year

### ISSUE THREAD

**Issue by brs17** [system76/docs#260]
Copyright still says 2019. The footer is attempting to show the latest year with: `{{ site.time | date: '%Y' }}` but with no success.

**Comment by jacobgkau** [comment]
The footer is now showing 2020 on the support pages.

![Copyright1](https://user-images.githubusercontent.com/7199422/71755327-4a295580-2e47-11ea-87f2-825b84912fbf.png)
![Copyright2](https://user-images.githubusercontent.com/7199422/71755329-4bf31900-2e47-11ea-9ac0-104ff69ba995.png)
