### ISSUE TITLE
Updating cuda to version 10.2

### ISSUE THREAD

**Issue by miguelcarcamov** [system76/docs#266]
A time ago the version 10.2 of CUDA came out. I was wondering if there is going to be a possibility to update to that version from pop OS.

Best regards

**Comment by mmstick** [comment]
It's currently packaged for 19.10; not yet for 18.04

**Comment by miguelcarcamov** [comment]
Is there an estimated date to be packaged for 18.04?

**Comment by ahoneybun** [comment]
10.2 has been packaged and released: https://github.com/system76/docs/pull/283

**Comment by miguelcarcamov** [comment]
> 10.2 has been packaged and released: #283

you mean cudnn... is not the same as cuda. When you try to install system76-cuda-latest, this still tries to install cuda 10.1 and not 10.2
