### ISSUE TITLE
Documentation for dual-booting windows does not cover full-disk-encryption

### ISSUE THREAD

**Issue by josiah-roberts** [system76/docs#319]
My Darter Pro came from the factory with full-disk-encryption, and the docs for dual-booting Windows don't work. Specifically, I cannot shrink the partition.

https://support.system76.com/articles/dual-booting/

**Comment by veronicacary** [comment]
Hi there! Not sure if you're having this issue still, but I've dealt with this on other distros before. I think Pop!_OS uses LVM on LUKS (someone will surely correct me if I'm wrong), and I think you can do this from a live USB. There's some risk involved, though- I wouldn't describe it as a super easy process.

Regarding the documentation for this, there's a decent write-up over on Arch Wiki: https://wiki.archlinux.org/index.php/Resizing_LVM-on-LUKS. I'd be happy to give this a try and send over a pull request with an updated document for Pop!_OS. Not sure if there's a contributor guideline for the docs, but if there is, I'll gladly read through it!

**Comment by serundeputy** [comment]
https://github.com/system76/docs#edit-an-article
Looks like contributor guidelines are submit a PR.

I'm also trying to dual boot.
