### ISSUE TITLE
"Repair the Bootloader" instructions do not clearly explain which partitions to use

### ISSUE THREAD

**Issue by themrdjj** [system76/docs#323]
After a firmware update on my Thinkpad PopOS was gone from my boot menu and while I managed to fix it using the instructions at [https://support.system76.com/articles/bootloader/](https://support.system76.com/articles/bootloader/), I struggled quite a bit with the first two commands under [https://support.system76.com/articles/bootloader/#for-nvme-drives-2](https://support.system76.com/articles/bootloader/#for-nvme-drives-2) as I had to figure out myself which partitions to use. I think for newbies like me who just follow the instructions without really knowing what to do a clarification on this would be quite helpful. For myself I figured out that the first one had to be the existing PopOS root and the second one the existing PopOS boot partition. I don't really know what this means though so I'll let someone else edit this in the docs.

**Comment by Tiger862000** [comment]
Huh, after 5 months no fix? 
I struggle with the same problem. It is not clear which partitions to mount (regardless of the device type). The tutorial does NOT explain that nor does it give an example case. 
Whoever wrote the tutorial knows what to change. Please fix it for all scenarios. Thank you!

**Comment by DavidT3** [comment]
I agree with the other two comments here, it would probably take an hour at most to add the extra information, and a disclaimer that partition /dev/ names will be different depending on the OSs you have installed. Otherwise the article works perfectly when you figure out that trying to mount systemd to a Windows partition is not going to work...

**Comment by ahoneybun** [comment]
I'm working on fixing this in this branch:

https://github.com/system76/docs/compare/update-bootloader
