### ISSUE TITLE
missing AwesomeWM, Fluxbox, WindowMaker, etc.

### ISSUE THREAD

**Issue by nitrofurano** [system76/docs#34]
it’s missing other window managers, like AwesomeWM, Fluxbox, WindowMaker, PekWM, JWM, etc. - i use them a lot

**Comment by AprilElizabeth** [comment]
Hi,

Thanks for the feedback! Would you consider making a pull request and helping us document these additional window managers, along with any caveats to installation? Our articles are geared towards novice users, though we definitely take contributions from the advanced users in the community who are willing to help out!

**Comment by Xeboc** [comment]
We will keep this article as just listing the more popular and well used window managers for now.

Closing this issue.
