### ISSUE TITLE
bug on default lightdm Ubuntu’s theme

### ISSUE THREAD

**Issue by nitrofurano** [system76/docs#35]
when we have installed, for example, more than 10 window managers installed, the theme can’t list them all - this situation is quite annoying when we enjoy trying different window managers, and forces us to move files around /usr/share/xsessions/

**Comment by AprilElizabeth** [comment]
Hi, thanks for the feedback. I wasn't able to verify this on 16.04, though I do see an issue where the list of window managers will be cut off when using more than (n) window managers depending on your resolution. See attached for an example at 958x651 resolution. Is this the same as what you're seeing?

![bunty-2016-10-21-10-29-37](https://cloud.githubusercontent.com/assets/64333/19605671/8ba2b1a4-9779-11e6-8bee-ac64fb73375b.png)

**Comment by Xeboc** [comment]
Added a little more info about this particular issue in the article.  Thanks for pointing it out!
