### ISSUE TITLE
update upgrade pop page screenshots from 19.04 to 19.10

### ISSUE THREAD

**Issue by joemcl** [system76/docs#373]
Update the screenshots [here](https://support.system76.com/articles/upgrade-pop/) from 19.04 to 19.10 .

**Comment by leviport** [comment]
Probably better to update to 20.04 at this point

**Comment by leviport** [comment]
The upgrade button is found in slightly different places in 18.04 and 19.10, so it might be useful to include screenshots of both.

**Comment by ahoneybun** [comment]
Since both 19.04 and 19.10 are no longer supported I believe we should close this.
