### ISSUE TITLE
Pop!_OS Development Approach page is not linked properly from Roadmap page

### ISSUE THREAD

**Issue by denis-roy** [system76/docs#378]
From: [https://support.system76.com/articles/roadmap/](https://support.system76.com/articles/roadmap/)

Clicking on `Pop!_OS Development Approach page` leads to the following HTTP 404:

[https://support.system76.com/docs/pop-os-development-approach/](https://support.system76.com/docs/pop-os-development-approach/)

**Comment by Oymate** [comment]
@denis-roy  Is it still down?

**Comment by denis-roy** [comment]
@Oymate it is still 404 yes

"Support Article Not Found

Hmm…

This article doesn’t exist here. Try the Support page."

**Comment by Oymate** [comment]
Can you tell me your country name?(if you are comfortable saying)

**Comment by denis-roy** [comment]
Canada

**Comment by Oymate** [comment]
Hey,
Found [this](https://support.system76.com/articles/pop-os-development-approach/) I think the link changed :)

**Comment by Oymate** [comment]
@denis-roy Change the "docs" with "articles". The website is updated!

**Comment by denis-roy** [comment]
PR done. Thanks @Oymate :)

**Comment by brs17** [comment]
Going to keep this open as the link for the development approach here; https://support.system76.com/articles/roadmap/ needs to be fixed to the proper link as mentioned by @Oymate

**Comment by Oymate** [comment]
Fixed this issue at this commit.
https://github.com/system76/docs/pull/395

So, closing this.
