### ISSUE TITLE
Nvidia download error

### ISSUE THREAD

**Issue by CrisMorgantee** [system76/docs#381]
Hi,
The download link for Nvidia return this error:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below. 

<Error>
<Code>NoSuchKey</Code>
<BucketName>pop-iso</BucketName>
<RequestId>tx0000000000000e6f5c129-005ebea442-443fd0-sfo2a</RequestId>
<HostId>443fd0-sfo2a-sfo</HostId>
</Error>
```

**Comment by lsatenstein** [comment]
I have a similar error. My monitor is operating at very low resolution (720x xxxx).
I will be trying to perform the system76 nvidia option

**Comment by brs17** [comment]
CDN cache has been cleared, your issue should no longer persist. Can you confirm that it now works? Also, can you verify you are in Canada?

**Comment by lsatenstein** [comment]
Look at my signature. 


Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

 

    On Monday, May 18, 2020, 2:07:31 p.m. GMT-4, Ben S <notifications@github.com> wrote:  
 
 


CDN cache has been cleared, your issue should no longer persist. Can you confirm that it now works? Also, can you verify you are in Canada?

**Comment by CrisMorgantee** [comment]
Solved!
Was one error on my provider internet!
Can I close this issue?

**Comment by brs17** [comment]
Issue was CDN related, not related to your provider but has been resolved. Glad it works for both you now!

**Comment by lsatenstein** [comment]
Hi CristianoI just downloaded the .6 version and I will do a fresh --clean installation-- tonight
If you do not hear from me by tomorrow AM, close the issue.


Regards 
 Leslie
 Leslie Satenstein
Montréal Québec, Canada

 

    On Monday, May 18, 2020, 7:52:49 p.m. GMT-4, Cristiano Morgante <notifications@github.com> wrote:  
 
 


Solved!
Was one error on my provider internet!
Can I close this issue?
