### ISSUE TITLE
Could you indicate what the minimum disk space is for an installation

### ISSUE THREAD

**Issue by lsatenstein** [system76/docs#382]
I have a 2 tb drive. I do not need 2tb for popos. I would like to set aside 120gig, and leave the rest of the drive alone.
PopOS does not offer a "use free space" option.
Currently I am doing a manual installation without using the recovery partition. No choice. I have 1 TB of other data on that 2TB SSD.
Please see what you can do to improve the disk space utilisation.  A 120gig of free space should be more than adequate for POPOS.

And why is it mounting everyswap file on the system including the one created by your installer.

And by the way, I do like your version of Gnome over other versions around.

Thank you for a great concept and design.

**Comment by Norfolt** [comment]
Maybe making a new partition is a good idea/option?

**Comment by veronicacary** [comment]
I believe the document "install Pop" states that a minimum of 20 GB of storage is recommended.

Source: https://support.system76.com/articles/install-pop/

**Comment by ahoneybun** [comment]
20GB for a Pop install is indeed correct and it is the same amount for Virtual Machines as well.
