### ISSUE TITLE
Nvideo version does not recognize the nvidea card, monitor at wrong unsettable correct resolution

### ISSUE THREAD

**Issue by lsatenstein** [system76/docs#383]
History.
Installed the *.5 Nvidea version and it installed itself as 720x xxxx  This was not workable. I could not install software to restore the regular gt218 Geforce 210 U  340.108.
Today I attempted to install the *.6 Nvidia version and this time the monitor came up at 1024 x 1080.
(ratio 4:3)
I am not able to use the POPOS with this resolution.  
Fedora, Ubuntu, Suse, Arch all see the monitor as  1920x1080 with ration 16:9
My system    ASUS X470-pro-prime, amd2700x, 16gigs ram, nvidea graphics card geforce 210
I do not mind trying to help you out to get the bug fix. Let me know when I have a new iso to try.
 
Leslie in Montreal

**Comment by ahoneybun** [comment]
I would recommend moving this issue here:

https://github.com/pop-os/system76-driver

Since that goes over the building of the NVIDIA driver itself.
