### ISSUE TITLE
Universal Access Cursor Size causes user desktop crash

### ISSUE THREAD

**Issue by JDVila** [system76/docs#384]
Problem:

After hours of scouring the internet, and losing a few settings by rebuilding my user preferences from the advice [under "Move old configuration files out of the way" here](https://support.system76.com/articles/login-loop-pop/), I was able to reclaim my desktop without it constantly logging me out or suspending itself, by returning the universal access cursor size to its default setting. These issues were discovered oddly enough after installing and uninstalling Pithos, the Pandora radio client.

Initially, I thought this was an nvidia driver issue based on internal logs, but after reinstalling and rebooting drivers old and new / big and small, many times, no changes helped, even after following the steps detailed in "Move old configuration files out of the way", which at the very least let me log in for an extended period of time, and demonstrated that the issue was specific to my user profile. Finally, after resetting the cursor size, it stopped crashing.

Ways to replicate:

1. Set Universal Access Cursor Size to largest setting.
2. Install regular pop!_os updates.
3. Install and uninstall debian version of Pithos from pop store.
4. Open the terminal, and spin cursor around the screen rapidly until either the session ends and you are logged out, or the screen freezes and goes black and unresponsive.

This is a problematic issue on several levels, since it not only limits expected use of the OS, but it also causes additional issues for the visually impaired. Please let me know if there is anything else I can help you with. Thank you again for your time, patience, and such an excellent product - even with the bugs!

**Comment by ahoneybun** [comment]
Thank you for this report! It looks like this may need to be moved to this repo:

https://github.com/pop-os/pop

Since that effects the whole project not the support articles.

**Comment by storyaddict** [comment]
Closing. Issue should be opened/resolved on the Pop repo.
