### ISSUE TITLE
Upgrade to Jekyll 4

### ISSUE THREAD

**Issue by btkostner** [system76/docs#389]
Looks like version 4 was released. We should upgrade.

https://jekyllrb.com/docs/upgrading/3-to-4/

**Comment by ahoneybun** [comment]
You first.

**Comment by btkostner** [comment]
![](https://media1.tenor.com/images/030649b57b8f8e863bc1f3dbfb7ef42c/tenor.gif?itemid=16635199)

**Comment by btkostner** [comment]
Moved to Nuxt backend. Closing issue.
