### ISSUE TITLE
Desktop Issue

### ISSUE THREAD

**Issue by akashpapnai** [system76/docs#396]
Could not go to Desktop while anywhere on the screen.
`Super + D` doesn't work.

**Comment by leviport** [comment]
The Super + D shortcut is no longer a default in Pop!_OS. Can you let us know where you see it mentioned in documentation so we can update that?

Thanks!

**Comment by akashpapnai** [comment]
It's here:
https://support.system76.com/articles/pop-keyboard-shortcuts/
Search for " Show Desktop ".
And can you tell me the new shortcut for the same.
Thanks in advance.

**Comment by leviport** [comment]
Thanks, we'll get that updated! 

It wasn't replaced by anything, so if you want that shortcut back, you'll have to set it manually in the "keyboard shortcuts" section of Settings.

**Comment by akashpapnai** [comment]
Ok, Thanks.
It took sometime for me Search the correct word.
It's " Hide all normal window " just in case someone else read this.
