### ISSUE TITLE
Grammar issue on CUDA page

### ISSUE THREAD

**Issue by daMelody** [system76/docs#400]
https://support.system76.com/articles/cuda/

In the Not running Pop!_OS? section:

> The previous instructions will work with Pop!_OS out of the box but for Ubuntu and other Debian derivatives the following commands will need to be **ran** first:

"ran" should be "run" in this instance

**Comment by TheEvilSkeleton** [comment]
Are you sure?

If we change the verb to something like "paid", it will be:

[...] will need to be paid first

and not

[...] will need to be pay first

**Comment by ahoneybun** [comment]
@storyaddict what are your thoughts?

**Comment by storyaddict** [comment]
@daMelody is correct. The correct sentence should be: "The previous instructions will work with Pop!_OS out of the box, but for Ubuntu and other Debian derivatives, the following commands will need to be run first:"

Or more simply:

"The previous instructions will work with Pop!_OS out of the box, but for Ubuntu and other Debian derivatives, run the following commands first:"
