### ISSUE TITLE
Dash to Dock page needs note re. broken for Pop!_OS 20.04

### ISSUE THREAD

**Issue by drscotthawley** [system76/docs#402]
The file docs/_articles/dash-to-dock.md should say something about how it no longer works once you update to to Pop!_OS 20.04.  Instead the Gnome Extensions page https://extensions.gnome.or just shows "ERROR" and the Extensions menu for Setup show a slider for Dash to Dock that does not respond when you click on it.

![dashtodock](https://user-images.githubusercontent.com/13925685/84545693-4a1a6500-acc5-11ea-95e3-89e54eedfa89.png)
![dashtodock2](https://user-images.githubusercontent.com/13925685/84545697-4d155580-acc5-11ea-9184-860c0d3b99fc.png)

**Comment by drscotthawley** [comment]
The note in the docs could say that if one downloads the source from https://github.com/micheleg/dash-to-dock/tree/gnome-3-36 
and installs manually, then this restores functionality to the Dock.

**Comment by veronicacary** [comment]
Dash to Dock is working as expected on my device (Galago Pro running Pop!_OS 20.04).

**Comment by ahoneybun** [comment]
It sounds like it is working so far in @veronicacary 's testing, can you confirm @drscotthawley ?

**Comment by drscotthawley** [comment]
It's working on mine because I build from source.  I am not willing to disable my build and retry the default now that I got it working on my machine.  Feel free to close this issue if no other users are experiencing problems.

**Comment by jacobgkau** [comment]
Confirmed Dash to Dock installs and starts on a Pop!_OS 20.04 system:

![Screenshot from 2021-02-24 15-53-25](https://user-images.githubusercontent.com/7199422/109076864-80174200-76b8-11eb-8318-7c9f64252be8.png)

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).
