### ISSUE TITLE
Activation of network failed

### ISSUE THREAD

**Issue by chilskater** [system76/docs#410]
I can detect my Alfa AWU036EAc with RTL8812AU chip. I managed to install the driver via these steps:
First, a little clean-up.

sudo apt purge rtl8812au-dkms

sudo apt update

sudo apt upgrade

dpkg --list | grep linux-image | awk '{ print $2 }' | sort -V | sed -n '/'`uname -r`'/q;p' | xargs sudo apt -y purge

sudo apt autoremove

sudo shutdown -r now

Then, install some build tools, download the source, build and install it.

sudo apt install build-essential git

git clone https://github.com/gnab/rtl8812au.git

cd rtl8812au

make

sudo make install

sudo modprobe 8812au

PROBLEM:
It detected my wifi network but cant connect. "Activation of network failed" error. I need to plug out and plugin again in order for it to detect my wifi network.It will connect to my 5ghz network but not m 2.4Ghz. If i disconnected it and select 2.3Ghz, it wont connect again to 5 Ghz if i choose 5 Ghz.
I didnt use rtl8812au-dkms found it Pop Shop

**Comment by ahoneybun** [comment]
This would be an upstream issue with GNOME/Ubuntu though this issue isn't really tied to the support articles. I would open an issue here instead: https://github.com/pop-os/pop then we can sort it to the correct project.
