### ISSUE TITLE
Netflix info outdated

### ISSUE THREAD

**Issue by fleskesvor** [system76/docs#422]
The following article on installing Flash to watch Netflix is outdated, since Netflix haven't used Flash in at least a couple of years:

https://support.system76.com/articles/flash/

In fact, I don't think any of the most popular streaming services do, since I have four different subscriptions, and none of them require Flash.

The solution instead is to install the `libavcodec-extra` package, and to let your browser of choice install the required addons for HTML5 DRM/Widewine support (works out of the box in Firefox). It would also be convenient if `libavcodec-extra` was already provided in the non-free iso though, as that would give an out of the box solution for Netflix in Pop!_OS.

**Comment by ahoneybun** [comment]
There was a big update to that article and where it was renamed here:

https://support.system76.com/articles/protected-content/

Do you believe it would still be a good idea to add a section to install that package?

**Comment by storyaddict** [comment]
Closing due to lack of response.

**Comment by fleskesvor** [comment]
> Closing due to lack of response.

Sorry for the late response. I rarely use GitHub outside of work because of its proprietary nature.

The new article looks much better. 👍 I only wish the section about Firefox wasn't tucked away at the bottom, since it's the default browser, and it works great with DRM protected streaming services. No need to install Chrome.
