### ISSUE TITLE
Update System Firmware page outdated

### ISSUE THREAD

**Issue by Zooce** [system76/docs#425]
https://support.system76.com/articles/system-firmware/ is outdated in the following ways (note I'm using an Adder WS -- addw2):
1. There's no Settings > Devices > Firmware. It's now Settings > Firmware.
2. The Settings > Firmware page does not have an Update button (maybe this is because my firmware was up-to-date?).
3. The `system76-firmware-cli` utility was not installed by default on my system. I had to run `sudo apt install system76-firmware` to get it.
4. Step 7 did not apply to my machine. Maybe it does apply to others?
5. The first part of Step 8 happened automatically (the BIOS was launched without me doing anything). For the second part of Step 8 (the Exit tab), there's a step missing which is to enter the Setup Utility.
6. In Step 9, there was no Load Setup Defaults, only Load Optimal Defaults. Maybe this is machine specific?

**Comment by Zooce** [comment]
If someone can comment on these issues and let me know if there's anything I'm missing or need to clarify, I'm more than willing to open a PR for this.

**Comment by Socialhappiness** [comment]
@Zooce Thank you for bringing this to our attention. The article has been updated.
