### ISSUE TITLE
Low key wording issue in darp5-service-manual.pdf

### ISSUE THREAD

**Issue by c4mmartin** [system76/docs#438]
in the darp5 service manual: docs/service-manuals/pdfs/Darter/darp5-service-manual.pdf
Page 25 shows the card as an (A key). I believe this should say (E key). Mine appears to be, also may be possible to note that a (key ea) card is likely compatible as i am now running an ax200 (key ea) after assumed card failure. Apologies if i am missing something simple.

**Comment by ahoneybun** [comment]
@jacobgkau can you see if this does need to be swapped?
