### ISSUE TITLE
Back button or more clear way to return to support page from a doc

### ISSUE THREAD

**Issue by ryanleesipes** [system76/docs#45]
I have this issue where I am reading through a tutorial and then click the System76 logo to go back, and that is not how to do it. Instead, you need to click the little support lifesaver icon. I don't like this. We need a big ole' back button or something like that in order to ensure folks who are reading through our support articles can easily go back to the main support page.

This is especially important if they read through the article and still need to open a support ticket. Let's make it super easy to navigate the support area.

**Comment by kylerschin** [comment]
Cool!

**Comment by Xeboc** [comment]
This will be addressed at some time.  On hold for now.
