### ISSUE TITLE
"Windows" key + L is still listed as screen lock

### ISSUE THREAD

**Issue by aaronmosey** [system76/docs#454]

**Comment by notoriousVKC** [comment]
Should this be listed as "Super-L" instead? Is there a standard naming convention that should be used in the docs?

IMO, so many folks coming from Windows still call it a "Windows" key, so I'm not opposed to language that reflects this (especially in documentation).

**Comment by aaronmosey** [comment]
Except that it doesn't lock the screen. The wording is not the issue.

**Comment by veronicacary** [comment]
Super-L is locking the screen on my Galago Pro running Pop!_OS 20.04. It's been a bit since I configured this device but I don't think I modified this behavior from stock Pop shell.

**Comment by aaronmosey** [comment]
The latest version (20.04 LTS?) uses super-esc
https://support.system76.com/articles/pop-keyboard-shortcuts/

**Comment by jacobgkau** [comment]
@aaronmosey Thank you for opening an issue. The article that you linked (https://support.system76.com/articles/pop-keyboard-shortcuts) is already correct and states that `Super`+`Esc` locks the screen. Where are you seeing the old shortcut still listed? Is it lower down on the same page under the `Pop!_OS (up to 19.10 release) Shortcuts` section, or is it in another article?
