### ISSUE TITLE
Referencing community-supported distros?

### ISSUE THREAD

**Issue by shlevy** [system76/docs#467]
The 20.09 release of the NixOS distribution will have a module for system76-specific support, including running the `system76-firmware-daemon`, installling the out-of-tree kernel modules, and packaging up `firmware-manager`. I doubt we're alone in having some of this available. Is there interest in documenting on the relevant pages (e.g. the firmware update page) that certain distros have community supported options?

**Comment by jackpot51** [comment]
Absolutely, we would be interested in this.

**Comment by shlevy** [comment]
@jackpot51 Great! Any guidance about where/how to put this? I can just take a stab at adding it in myself if not.

**Comment by jackpot51** [comment]
Usually these would go in Community Articles on https://support.system76.com/

**Comment by shlevy** [comment]
Sounds good, will take a look!
