### ISSUE TITLE
Explain how to repair file systems

### ISSUE THREAD

**Issue by MikhailTNY** [system76/docs#487]
I didn't see any Pop! articles on this, the google search was mostly for non-LUKS setups. 

My file system got marked as read-only and I couldn't figure out why. The recovery partition helped get me in there but it turns out that by mounting the file system, it wasn't allowing me to do anything with fsck. 

I ended up just going the GUI way, which is to (summarized as I can't recall all details):

1. Open Disks from Activities
2. Select the locked drive to unlock and then enter your disk passphrase
3. Select the unlocked disk on the sidebar and then click the gears icon to select repair file system. 

I would prefer to do this via terminal but it was confusing to figure it out and I really needed to get back in quickly .

**Comment by ahoneybun** [comment]
This is a great article idea! I'll get this added to our Trello board!

**Comment by ahoneybun** [comment]
Here is the PR and WIP: https://github.com/system76/docs/pull/563

**Comment by MikhailTNY** [comment]
@ahoneybun thanks for starting the work on this. I looked at the PR but it doesn't go far enough. Pop!_OS encrypts the drive by default, which is why I got stuck on this in the first place. You have to go through the process of booting into the recovery mode [link to the article on how to do this](https://support.system76.com/articles/pop-recovery/) and then open the Disks app, find the correct locked drive and decrypt it before you repair it.

**Comment by ahoneybun** [comment]
Right now it links to the live disk and bootloader articles that do go over decrypting the drive to fix the file system. It is still a work in progress but that you for the feedback and great idea!

**Comment by storyaddict** [comment]
PR merged. Issue resolved.
