### ISSUE TITLE
"Install DaVinci Resolve" instructions with AMD graphics

### ISSUE THREAD

**Issue by curiousercreative** [system76/docs#490]
### Issue
The current instructions for installing latest AMD drivers (20.40) required for DaVinci Resolve are not compatible with pop_os (20.04) or kernel version (5.8.0-7625-generic).

1. pop_os is unsupported
    ```bash
    $ sudo ./amdgpu-pro-install -y --opencl=legacy,pal
    Unsupported DEB-based OS: /etc/os-release ID 'pop'
    ```
   If you replace `pop` with `ubuntu` in /etc/os-release, then you get further...
1. kernel version unsupported by AMD driver kernel modules

- https://support.system76.com/articles/install-davinci-resolve/
- https://github.com/system76/docs/blob/master/_articles/install-davinci-resolve.md#install-prerequisite-packages

**Comment by alexeyzimarev** [comment]
Yeah, adding `pop` to the script is easy but the compatibility issue is there:

```
ERROR (dkms support): kernel package linux-headers-5.8.0-7625-generic is not supported.
```

Pop!OS 20.10

**Comment by ahoneybun** [comment]
@alexeyzimarev and @curiousercreative can you get logs? There should be a make.log file in that error page. Those kernel versions are pretty old as well so I would test with the newest kernel.

**Comment by curiousercreative** [comment]
@ahoneybun unfortunately, I gave up and traded the AMD card out for an NVIDIA card. I do have an AMD card I could install alongside the NVIDIA card. Is it recommended to have drivers for both installed?
