### ISSUE TITLE
Any plan for  system76-cuda-11+？

### ISSUE THREAD

**Issue by Babylonehy** [system76/docs#494]

**Comment by ahoneybun** [comment]
We have updated the CUDA packages and added 11+ versions as you can see here:

aaronh@pop-os ~/g/docs (master)> apt search system76-cuda
Sorting... Done
Full Text Search... Done
system76-cuda/groovy 0pop1 amd64
  NVIDIA CUDA Compiler / Libraries / Toolkit Metapackage

system76-cuda-10.0/groovy 0pop0 amd64
  NVIDIA CUDA 10 Compiler / Libraries / Toolkit

system76-cuda-10.1/groovy 0pop0 amd64
  NVIDIA CUDA 10 Compiler / Libraries / Toolkit

system76-cuda-10.2/groovy 0pop1 amd64
  NVIDIA CUDA 10 Compiler / Libraries / Toolkit

system76-cuda-11.1/groovy 0pop1 amd64
  NVIDIA CUDA 11.1 Compiler / Libraries / Toolkit

system76-cuda-11.2/groovy 0pop1 amd64
  NVIDIA CUDA 11.2 Compiler / Libraries / Toolkit

system76-cuda-latest/groovy 11.2~20.10 all
  Metapackage for the latest version of the CUDA Toolkit

**Comment by emremrah** [comment]
I would like to use tensorflow with GPU. I tried with `system76-cuda-11.1` and `system76-cuda-11.2` with tensorflow 2.4.0 but seems like it only developed and tested on cuda 11.0. Is it possible to install 11.0 from `system76-`?

The error I get is: *Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory*

**Comment by ahoneybun** [comment]
There aren't any plans on updating packages for CUDA and Tensorflow since we created Tensorman to handle those setups. You can read more about Tensorman here:

http://support.system76.com/articles/tensorman/

**Comment by SaiSandeepKantareddy** [comment]
It is always installing 11.4 cuda although trying to install 11.1

**Comment by blais** [comment]
> There aren't any plans on updating packages for CUDA and Tensorflow since we created Tensorman to handle those setups. You can read more about Tensorman here:

This would be REALLY useful to mention on your pages at
https://support.system76.com/articles/cuda/

I just wasted a bunch of time trying to work with the system76 versions [Thelio Mira owner w/ Ryean and RTX3060] to make Jax work and was giving up and installing straight from nvidia and ended up here.

Please also mention it here:
https://github.com/system76/cuda

**Comment by ahoneybun** [comment]
I'm addressing that in this PR: https://github.com/system76/docs/pull/1062
