### ISSUE TITLE
System76 Oryx Pro: laptop isn't even starting

### ISSUE THREAD

**Issue by Ruijen** [system76/docs#496]
Yesterday my laptop started out fine, when I got done using my laptop I shut it down. But this morning my laptop isn't even starting up. I would power it on, the power button on it is on, then the light at the bottom would be green for a little bit but then turn orange and start flashing and then my power goes off again. Don't know why its doing it. Looking for some help.
FYI: the flashing light is the prong symbol/ power.

**Comment by leviport** [comment]
Hi @Ruijen, sorry to hear your Oryx is misbehaving. You should contact the [support team](https://support.system76.com) so they can assist you in getting it back up and running. Github isn't the best place for product support, and you'll get much better help in a support ticket.
