### ISSUE TITLE
'20.04' written, when '20.10' intended

### ISSUE THREAD

**Issue by DougInAMug** [system76/docs#498]
There seems to be an error in the page instructing people to upgrade from 20.04 to 20.10. After all the installation steps it is written:

> After the upgrade is finished, you will be taken back to the login page, and voila! Your system is now running Pop!_OS **20.04**! 

(emphasis added.)
 
I think this should read '20.10' instead!

**Comment by jacobgkau** [comment]
Fixed by https://github.com/system76/docs/pull/486. (Would have also been fixed by https://github.com/system76/docs/pull/492 and https://github.com/system76/docs/pull/484 -- thanks to everyone who submitted PRs for this.)
