### ISSUE TITLE
confusion in cudnn 10-2 actually referring to 7.6.5

### ISSUE THREAD

**Issue by johndpope** [system76/docs#509]
system76-cudnn-10.0 (7.6.5)
https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html

https://github.com/pop-os/pop/issues/844

https://support.system76.com/articles/cuda/

https://github.com/system76/docs/compare/master...johndpope:patch-1

**Comment by mmstick** [comment]
As of today, 10.1 and higher are now 8.0.4

**Comment by johndpope** [comment]
makes sense - just need clarity on docs alluding to this. It's a razer edge of installing wrong cuda on backwards systems. I'd prefer to use the latest - but in my edge case - I need to get tensorflow1- gpu working - which supposedly only supported on cuda 10 + 7.4 / though it probably works on later stuff?  https://www.tensorflow.org/install/source#tested_build_configurations

tensorflow_gpu-1.15.0 | 2.7, 3.3-3.7 | GCC 7.3.1 | Bazel 0.26.1 | 7.4 | 10.0
-- | -- | -- | -- | -- | --

**Comment by mmstick** [comment]
Tensorflow for sure is complicated, hence why we recommend using Tensorman to use Tensorflow from within a Docker container, which already has the precise system libraries and CUDA SDKs that each particular image was built for.
