### ISSUE TITLE
Create HOWTO for adding "compatible" Desktop Environments

### ISSUE THREAD

**Issue by SaintDanbert** [system76/docs#529]
Linux as a whole has multiple Desktop Environments (DE) available in the repositories and from their respective project sites.  Which are known compatible with both POP and Ubuntu?  The preferred way to install and configure these DE might be available in some sort of HOWTO document.

In the case of DE that are good-to-go out of their respective packages, a simple link to the DE package specific document pages might be good enough.

**Comment by ids1024** [comment]
Is this article roughly what you're looking for?: https://support.system76.com/articles/desktop-environment/

Though any desktop environment other than the default is not as well supported.

**Comment by Socialhappiness** [comment]
It looks like this was resolved with an existing article! Please open a new issue if you have any questions. We appreciate your support!
