### ISSUE TITLE
CUDA Article Errors

### ISSUE THREAD

**Issue by alelopezperez** [system76/docs#531]
There are few errors in the CUDA Article which are:

**cuDNN Library version not compatible with  system76-cuda-latest:**
- The version specified in the article is  system76-cudnn-10.2 which do not coincide with the version system76-cuda-latest installs (11.2) . 
- system76-cudnn-11.1 is available in the repo. So maybe we should update the command from
 `sudo apt install system76-cudnn-10.2` to `sudo apt install system76-cudnn-11.1`
- Since the cuDNN version is different from cuda-latest it install cuda 10.2. So now I have two versions of cuda.

**The file cat /usr/lib/cuda/version.txt does not exist. The structure goes like this**
- /usr/lib/
-- cuda (this one does not contatin version.txt)
-- cuda-11.2 (this one does not contain version.txt)
-- cuda-10.2 (this folder contains version.txt)

Since cuda-10 was installed for cuDNN-10 installation I think that's why we have the two folders.

**Restart requiered**
- I ran `sudo apt install system76-cuda-latest` and `sudo apt install system76-cudnn-10.2` in integrated graphics mode and nvcc was not available until I restarted my computer; and the article does not mention a need for a restart.

Suggestions:

- update the cuDNN from 10.2 to 11.1
- remove `cat /usr/lib/cuda/version.txt` as a way to see the current version of cuda. 
- For the restart issue further testing in the other graphics mode is needed to know If those modes require a restart.

- long term fix, create a `system76-cudnn-latest` meta-package so cuda and cuDNN be compatible.

**Comment by ahoneybun** [comment]
@mmstick what are your thoughts on this issue?

**Comment by mmstick** [comment]
If the intention is to use cudnn installing `cudnn-XX.Y` is enough to install both cuda and cudnn. But when developing applications with CUDA, you have to use the version of CUDA that's supported by what you're working with, so which version you pick is dependent on your use case. So there really isn't much point in having a `latest` metapackage.

**Comment by ahoneybun** [comment]
@alelopezperez do you believe that addresses your issue/question?

**Comment by ahoneybun** [comment]
I'm closing this as it sounds like this is corrected but please do let us know if that is incorrect @alelopezperez .
