### ISSUE TITLE
Wake on Lan with Ethtool Settings Disappear on Restart

### ISSUE THREAD

**Issue by Rav8es** [system76/docs#558]
WoL setting disappears after restart. 

sudo ethtool -s INTERFACE wol g

On restart interface is back to d. I’m forced to write a script to make this stick. The setting doesn’t disappear for me in Ubuntu or Kubuntu.

**Comment by jacobgkau** [comment]
Is this an issue with one of the articles in this documentation repository, or are you trying to report an issue in Pop!_OS? The general Pop!_OS repository is located here: https://github.com/pop-os/pop/issues/

**Comment by Rav8es** [comment]
This is not an issue found in the docs. I must have posted in wrong issue repo.

Sent from my iPhone

On Feb 24, 2021, at 4:16 PM, Jacob Kauffmann <notifications@github.com> wrote:

﻿

Is this an issue with one of the articles in this documentation repository, or are you trying to report an issue in Pop!_OS? The general Pop!_OS repository is located here: https://github.com/pop-os/pop/issues/<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpop-os%2Fpop%2Fissues%2F&data=04%7C01%7C%7Cd11fd91308a0450b880e08d8d9097db0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637497982073443156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pXq%2B6BYoFVvWaJ6GHqcQqC2%2FEHqVA0d5pDIZ3cLf19A%3D&reserved=0>

**Comment by jacobgkau** [comment]
I found an open issue in the Pop repository regarding Wake-on-LAN not working: https://github.com/pop-os/pop/issues/866 

Please work within that issue or open one in the correct repository if it doesn't sound like the same issue.

**Comment by Rav8es** [comment]
Thank you and my apologies for posting in the wrong repo.
________________________________
