### ISSUE TITLE
Arabic keyboard support

### ISSUE THREAD

**Issue by MuntherJaber** [system76/docs#571]
I'm having a problem with the Arabic keyboard. The keys seem to be mapped randomly.

**Comment by ahoneybun** [comment]
@leviport @jacobgkau do you know where this would be filed for the Pop project?

**Comment by bflanagin** [comment]
@MuntherJaber: We'll be happy to look into the issue but we're going to need you to submit this issue over at our Pop!_OS repo here on github. https://github.com/pop-os/pop/issues

Try to fill out as much information as you can about the problem so we can help you further.
