### ISSUE TITLE
Instructions on how to enable automatic updates

### ISSUE THREAD

**Issue by kolgza** [system76/docs#573]
Since there is no GUI setting to enable automatic updates, there should be a support page on how to:

- [Install and configure `unattended-upgrades`](https://linoxide.com/enable-automatic-updates-on-ubuntu-20-04/)
- Create a systemd timer to automatically execute `flatpak update -y`

**Comment by storyaddict** [comment]
Cross referencing with this: https://github.com/pop-os/upgrade/issues/217

**Comment by ahoneybun** [comment]
Pop now has automatic updates as of 22.04 so I believe we can close this.
