### ISSUE TITLE
Unable to start pop_os! after bios update

### ISSUE THREAD

**Issue by jachavarri** [system76/docs#579]
I installed pop_os! and Windows 10 following the instructions on [the article dual-booting](https://support.system76.com/articles/dual-booting/). I managed to install both operating systems on the same drive, so they both start up fast.

Everything worked just fine, if I pressed the power button it would load pop_os!, and if I holded the space bar I was able to load Windows... Until I updated the bios...

I got a message on Windows for the update. After the update was done, my computer restarted directly into Windows. When I entered the bios to check the start up options, I realized the only option available was to use the Windows' Manager, the pop_os! manager was gone.

Is there a solution to my problem? How do I recover the dual boot menu?

If you need more info, please let me know.

**Comment by ahoneybun** [comment]
You will have to reinstall the bootloader (systemd-boot) in this case. When updating the BIOS Windows will reinstall the Windows Boot Manager which messes with systemd-boot.

**Comment by jachavarri** [comment]
Awesome! I followed [this instructions](https://support.system76.com/articles/bootloader/) and it worked perfectly.

Thanks!
