### ISSUE TITLE
Unable to locate package pop-desktop

### ISSUE THREAD

**Issue by Devdre1909** [system76/docs#580]
I presently have Ubuntu 20.04 installed on my Machine, and I wish to install and use the Pop OS desktop environment, according to the instructions [here](https://support.system76.com/articles/desktop-environment/). After running the command 
`sudo apt install pop-desktop`
I keep getting 
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package pop-desktop`

**Comment by ahoneybun** [comment]
That package would only be available if you have the Pop PPA added to the system which we don't recommend to do on Ubuntu as it will replace other key packages as well.

**Comment by Devdre1909** [comment]
Oh, okay, thank you. 

So, it not possible for me be using Pop OS alongside Ubuntu

**Comment by ahoneybun** [comment]
You can dual boot both OSes that's certainly possible that to set up.
