### ISSUE TITLE
Clarify general applicability of graphics/power settings in docs

### ISSUE THREAD

**Issue by metasoarous** [system76/docs#591]
The page on switching power/graphics profiles reads

> The following laptops have switchable graphics:
>
> Adder WS (addw1, addw2)
> Galago Pro (galp5 - NVIDIA models only)
> Gazelle (gaze14, gaze15)
> Oryx Pro (oryp4, oryp4-b, oryp5, oryp6)

Given that many people arriving at this documentation page may be using non-System76 hardware, it may be helpful to more clearly spell this out.

**Comment by ahoneybun** [comment]
Thank you for the feedback! Are we looking to add System76 to the front of those products or something else? We can't confirm what models from other OEMs have working switchable graphics though.

**Comment by metasoarous** [comment]
Hi @ahoneybun. Thanks for your response.

Somehow, I thought I had created a PR out of the commit referenced above, but never did. See #597 for my suggestion about how the general utility of the functionality could be made clearer.

Thanks again
