### ISSUE TITLE
How to take a full-disk image (revise backups)

### ISSUE THREAD

**Issue by gangwerz** [system76/docs#622]
Article for how to take a full disk image
GNOME Disks
Clonezilla?

**Comment by smth-0** [comment]
Gnome disks is a very nice tool. Creates img images of disks in a snap. 
I think maybe I will be able to write that into a nice article. Will open a PR if I make it

**Comment by storyaddict** [comment]
@gangwerz @vega-d I think this will work better as an update to the [Backups](https://support.system76.com/articles/backup-files) article. Please aim PRs at that.

**Comment by vega-d** [comment]
Opened a pull request addressing this. #762
