### ISSUE TITLE
Add Update Recovery to Pop-Recovery

### ISSUE THREAD

**Issue by gangwerz** [system76/docs#667]
A GUI method to update Pop Recovery has been added to 20.04 and 21.04 (not 20.10). Add information on how to update (GUI and CLI), as well as what it does and why you want to keep it updated (Refresh install option is the big one I can think of)

**Comment by jacobgkau** [comment]
> 20.04 and 21.04 (not 20.10)

The pop-upgrade update went out to all versions we're still able to update, including 20.10 (and 18.04).
