### ISSUE TITLE
Add xorg.conf reset as suggestion for solving "black screen" problem

### ISSUE THREAD

**Issue by josephrocca** [system76/docs#674]
I had a problem with my adderws laptop screen being black/blank when I booted up, and I went through the trouble-shooting steps [listed here](https://support.system76.com/articles/login-loop-pop/). None of them worked, but I eventually solved it thanks to [this](https://askubuntu.com/questions/1059965/internal-laptop-screen-not-detected-when-using-nvidia-driver) AskUbuntu post. The solution was just to delete the `xorg.conf` file:
```
mv /etc/X11/xorg.conf /etc/X11/xorg.conf.old
```
Might be worth adding to the aforementioned docs article?

**Comment by storyaddict** [comment]
@josephrocca thanks for bringing this our attention. I think this is a good addition to include.
