### ISSUE TITLE
Create a Gaming Master Article

### ISSUE THREAD

**Issue by storyaddict** [system76/docs#686]
https://support.system76.com/articles/steam/

https://blog.system76.com/post/641571610853326848/the-system76-guide-to-gaming-on-popos?utm_source=system76&utm_medium=email&utm_term=Gaming411&utm_content=LinuxGamingBlog1&utm_campaign=newsletter

**Comment by ahoneybun** [comment]
Being worked on in this PR:

https://github.com/system76/docs/pull/688
