### ISSUE TITLE
In-line code blocks are not rendering

### ISSUE THREAD

**Issue by gangwerz** [system76/docs#698]
The single back-tick sections in the support articles are not being rendered properly. They now show in bold, with the back-ticks showing as part of the text

> > I am not seeing anything wrong with the article. However, the new Markdown to HTML compiler/transpiler has not been rendering in-line code (single back ticks), so any of those sections may need to be rewritten.
> 
> Should I just make it bold or do we have an option for an equivalent feature?

I think we should share with the team, cause it may require updating most articles, or another update to the markdown processor
Example on the live site: https://support.system76.com/articles/terminal-basics/

_Originally posted by @gangwerz in https://github.com/system76/docs/issues/678#issuecomment-867154597_

**Comment by gangwerz** [comment]
@storyaddict @ahoneybun Tagging you both to bring eyes to this

**Comment by btkostner** [comment]
This has been fixed in our styles. Thanks for the report @gangwerz!
