### ISSUE TITLE
Add Stress Tool to `hardware-failure` Article

### ISSUE THREAD

**Issue by gangwerz** [system76/docs#705]
The `stress` tool should be added for CPU testing. Warn users of high temps and fan noise when benchmarking

**Comment by leviport** [comment]
`s-tui` is a pretty neat ncurses interface for `stress-ng`. Might be worth mentioning if you're talking about those kinds of programs.

**Comment by SrPennywise** [comment]
Please add at head of article: During Hardware stress testing you may experience High fan noise and temperatures as well as slow system performance.

Please add "Nvidia cards with CUDA only" for GPU burn

Please add a section on CPU stress testing: Stress

sudo apt -y install stress && i=$(nproc) stress -c $i -m $i

**Comment by gangwerz** [comment]
@leviport rocked @SrPennywise's world with `s-tui`, so I think it definitely should make the article

**Comment by ahoneybun** [comment]
I made a Draft PR for these changes here: https://github.com/system76/docs/pull/707

**Comment by storyaddict** [comment]
Changes made [here](https://github.com/system76/docs/pull/707)
