### ISSUE TITLE
Create a Workspace Picker Shortcut Keybinding

### ISSUE THREAD

**Issue by geekmdtravis** [system76/docs#727]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

Currently selecting the Workspace Picker in PopOS! 21.04 (GNOME 3.38.5) requires either searching for it or manually clicking it's icon in the dock with a mouse. This is a departure in functionality from the prior version of PopOS! It's really one of many changes, but this one feels like a significant negative in PopOS!'s otherwise unrivaled workflow. 

For clarification, the Workspace Picker both allowed for a quick overview of the state of the extended desktop. So, even if not rearranging, it was often useful to get an overview of the state of the desktop. Additionally, it allowed for an easy rearrangement of the location of applications in the various workspaces. 

Previously selecting the **super** button would display a combination menu with search, apps, and the Workspace Picker. This has been changed, and now there are only keyboard shortcuts to show the application menu and the launcher. A keyboard shortcut to display the Workspace Picker does not exist, at least apparently does not exist, and this is despite a review of the updated documentation on the PopOS! website and the on-PC documentation of the keyboard shortcuts.  

* **What is the expected behavior?**
A keyboard shortcut would ideally exist that would launch the Workspace Picker. This would also ideally be documented.

* **What is the motivation / use case for changing the behavior?**
Restore high-value workflow functionality that was lost upon upgrading to PopOS! 21.04. 

* **Please tell us about your environment:**
  
  - Version: PopOS! 21.04
  - GNOME Version 3.38.5
  - Intel Core i9-10885H
  - 64 GB DDR4
  - RTX 2060

**Comment by ahoneybun** [comment]
You can either set the Workspace Picker as the behavior for the Super key in Settings -> Desktop or you can press Super+D if you have Super on it's own set to something else. I do need to add that shortcut to the documentation.

**Comment by geekmdtravis** [comment]
> You can either set the Workspace Picker as the behavior for the Super key in Settings -> Desktop or you can press Super+D if you have Super on it's own set to something else. I do need to add that shortcut to the documentation.

Wonderful, thank you so much! I was not able to identify this shortcut, and this is a big-time workflow enhancement.

**Comment by ahoneybun** [comment]
Thank you for bringing this to our attention! We made the change here: https://github.com/system76/docs/pull/728
