### ISSUE TITLE
Add instructions on installing dependencies to `gpu-burn` in `hardware-failure.md`

### ISSUE THREAD

**Issue by randvoorhies** [system76/docs#752]
https://github.com/system76/docs/blob/master/content/hardware-failure.md

The instructions for building `cpu-burn` simply tell the user to clone the repo and run `make`, however it requires some dependencies to build:

```
some_user@some_system76_box:~/Downloads/gpu-burn(master)$ make
g++ -O3 -Wno-unused-result -I/usr/local/cuda/include -c gpu_burn-drv.cpp
gpu_burn-drv.cpp:51:10: fatal error: cuda.h: No such file or directory
   51 | #include <cuda.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:32: gpu_burn-drv.o] Error 1```

**Comment by storyaddict** [comment]
Hi @randvoorhies thanks for bringing this to our attention. We'll review this and update the article.

**Comment by storyaddict** [comment]
@randvoorhies could you share what your hardware configuration is?

**Comment by randvoorhies** [comment]
@storyaddict Sure thing:

```
System76 Model: oryp7
OS Version: Pop!_OS 21.04
Kernel Version: 5.11.0-7620-generic
```
