### ISSUE TITLE
Correction: Backup-files article

### ISSUE THREAD

**Issue by SrPennywise** [system76/docs#775]
Corrections need to be made to section on our support.system76.com/articles/backup-files article.
Our provided instructions will not work for imaging a OS drive.
1. Need to run the Gnome-disk-utility in a USB Live boot for creating and restoring a operating system drive image.
2. Target for the save location for new .img need to be to a bigger than the drive being imaged. Otherwise you will get an error if you try to copy a 1TB drive image to a 1TB drive saying that there isn't enough space in destination.

**Comment by ahoneybun** [comment]
So are these just notes about this section then? 

https://support.system76.com/articles/backup-files#create-and-restore-disk-images-using-disks-app

**Comment by SrPennywise** [comment]
for #1 

You cannot image a disk that is actively being used, so you need to image the entire disk while in a USB live boot using gnome disks

for #2 

The destination for the .image of the disk needs to be bigger than the image itself. So if your harddrive is 1TB you can only save the 1TB image to a 1.5Tb or 2TB drive
