### ISSUE TITLE
Stray "Windows" sub-heading

### ISSUE THREAD

**Issue by leviport** [system76/docs#803]
Found on https://support.system76.com/
![2021-10-15_08-35](https://user-images.githubusercontent.com/13512097/137505047-7ff95cf8-5e99-436a-a718-90f7125190b5.png)

My guess is that this is a side effect from https://github.com/system76/docs/pull/794

**Comment by storyaddict** [comment]
Fixed with PR https://github.com/system76/docs/pull/804
