### ISSUE TITLE
"Pop key" is a confusing way to refer to the super key

### ISSUE THREAD

**Issue by leviport** [system76/docs#827]
https://support.system76.com/articles/pop-keyboard-shortcuts/

![2021-11-09_09-49](https://user-images.githubusercontent.com/13512097/140968100-5ca688a4-b039-43fd-93ac-6fd72dab8413.png)

We've never made a product with the Pop!\_OS logo printed on the super key, so calling any key the "Pop key" is confusing and unnecessary. We should have an image of the symbol we use, and say "The super key is marked with this symbol"

Similarly, calling it the "Ubuntu key" might also be confusing since it's (correctly) referred to as the Super key throughout the rest of the article. Saying "The super key is marked with the Ubuntu logo" would make much more sense, in my opinion.

**Comment by ahoneybun** [comment]
We are working on this from this issue:

https://github.com/system76/docs/issues/806

With that said I'm looking to see how difficult it would be to scale an SVG in markdown since we can't call it like the Ubuntu logo currently.

**Comment by leviport** [comment]
I didn't see any mention of this issue in #806, but feel free to close this and add it to that issue if that's how you prefer to track it.

I'm not sure I understand the SVG issue. Both the Pop and Ubuntu logos in those articles are inline SVGs already, so wouldn't the super key symbol be done the same way? Let me know if you need Inkscape help though. I'm pretty decent at that kind of thing.

**Comment by leviport** [comment]
Ah ok, I didn't see #822, just #806. Feel free to close if I'm just making unwanted noise :loudspeaker:
