### ISSUE TITLE
All Chroot Articles Need Reminder for Internet

### ISSUE THREAD

**Issue by storyaddict** [system76/docs#835]
We need to make sure that customers are told to connect their live environment to the internet before copying over their resolv.conf file.

**Comment by Ampersandstorm** [comment]
@storyaddict These are the only two articles I could find mentioning the resolv.conf file. I can add this warning to both, but let me know if there are more: 

https://support.system76.com/articles/pop-recovery/
https://support.system76.com/articles/bootloader/

**Comment by storyaddict** [comment]
There's also this one: https://support.system76.com/articles/login-from-live-disk
