### ISSUE TITLE
how change paper type to photo glass in printer settings

### ISSUE THREAD

**Issue by saeedkh11** [system76/docs#859]
Hi. How can I change the paper type settings? There are only two types of paper in the settings. The printer model is Epson L 1110. With plain paper settings, the print quality on glossy paper or glossy photo is really awful.

**Comment by leviport** [comment]
Settings > Printers > gear button next to your printer > Printing options > Paper Type

For future reference, [our Pop!\_OS chat room](https://chat.pop-os.org) is a better place for support-related questions.
