### ISSUE TITLE
SMMSTORE Firmware article is missing newer models.

### ISSUE THREAD

**Issue by storyaddict** [system76/docs#861]
https://support.system76.com/articles/open-firmware-smmstore does not have links for newer systems like the Oryx 7 & 8, Gazelle 16, etc.

**Comment by jacobgkau** [comment]
The bug was fixed and this should not be necessary for newer models. If it's still happening, then the cause needs to be identified again.

**Comment by jackpot51** [comment]
Newer models can clear SMMSTORE by removing RTC battery for a bit.
