### ISSUE TITLE
gsd_keyboard is not like real thing, shift does not modify outside of gsd_keyboard app

### ISSUE THREAD

**Issue by dlarue** [system76/docs#878]
Hi, it looks like Gnome has decided to keep gsd_keyboard as only a test input device meaning the keys, shift, alt, ctl, esc do not effect apps outside of the keyboard.  And it does not operate like a keyboard where you can press-hold a key to kick off repeat mechanism and while holding down the key, press the Shift key to get the repeating key to switch to cap and release and go back to lower case.

I've even tried the keyboard extension but that too fails the same way.

I'm now looking at using a gesture to try and initiate a keyboard modifier but I can not find any information on the existing gesture system in Pop! OS 21.10 v3 but gestures is advertised during the install process.

If there is not setup for users to create new gestures, can this product be added on top of the builtin gesture system?
https://github.com/JoseExposito/touchegg

**Comment by ahoneybun** [comment]
The gestures are handled by touchegg and it looks like the config files are in ~/.config/touchegg so you should be able to add custom gestures there though I would use the documentation from the project here:

https://github.com/JoseExposito/touchegg#configuration

**Comment by dlarue** [comment]
I have been able to add my gestures by creating ~/.config/touchegg/touchegg.conf but it still looks like there are some 4 finger gestures active.  I found another config file in /usr/share/touchegg/touchegg.conf and I will try deleting that and see if it removes the incorrect gestures.
