### ISSUE TITLE
Clarify the meaning of the NVIDIA Hardware Table on the Windows support page

### ISSUE THREAD

**Issue by juvtib** [system76/docs#899]
I am interested in installing Windows 11 on the new kudu6 laptop. I was looking at the Windows support page for information. I'm *not* familiar with laptop drivers in general. For example, on my custom desktop, I always download and install drivers from nvidia.com. Also, I am not familiar with System76's product lineup. For example, I'm not sure if there is more than one product called Kudu. 

I want to know if the NVIDIA GeForce RTX 3060 in the Kudu will work on Windows 11. There is an NVIDIA Hardware Table on the Windows support page with headings that just say "Always", "Maybe", and "Never". The table lists "Kudu" under Never. It is not clear to me what this is shorthand for. For example, NVIDIA provides drivers for the 3060 Laptop GPU. But NVIDIA's page also mentions: 

> Although GeForce Game Ready Drivers and NVIDIA Studio Drivers can be
> installed on supported notebook GPUs, the original equipment manufacturer
> (OEM) provides certified drivers for your specific notebook on their website.
> NVIDIA recommends that you check with your notebook OEM for recommended
> software updates for your notebook.  

So does the "Never" column mean System76 will never provide an OEM driver? Or does it mean System76 thinks the 3060 Laptop GPU doesn't have a driver from NVIDIA? Or has someone tested the NVIDIA driver on the laptop and it doesn't work? Or is there some model mix-up? For example, Lemur and Meerkat are also under the Never column. Both use integrated graphics. And while Kudu has integrated graphics, it also has the discrete 3060 Laptop GPU. 

Please add an introduction to the NVIDIA Hardware Table. And make it clear what the table means. 

Thank you, 

* [NVIDIA Hardware Table](https://support.system76.com/articles/windows/#nvidia-hardware-table)
* [docs/windows.md at master · system76/docs · GitHub](https://github.com/system76/docs/blob/master/content/windows.md)
* [GeForce Game Ready Driver | 511.65 | Windows 10 64-bit, Windows 11 | NVIDIA](https://www.nvidia.com/Download/driverResults.aspx/186769/en-us)

**Comment by leviport** [comment]
The information in that article is stale. The Kudu is listed as never needing the Nvidia driver because kudu1 through kudu5 were integrated Intel graphics only, and did not even have Thunderbolt in order to support eGPUs. 

We haven't tested the kudu6 with Windows 11 yet since we don't ship Windows, but I don't think Windows 11 would have any problems on it.

**Comment by juvtib** [comment]
Thank you. If you don't need this issue as a placeholder then please close it
at your convenience. 

Regards,
Mike
