### ISSUE TITLE
Update Windows Compatibility Table

### ISSUE THREAD

**Issue by juvtib** [system76/docs#900]
I am interested in installing Windows 11 on the new kudu6 laptop. 

Please update the Compatibility Table at the top of the Windows support page with an entry for the kudu6. 

Thank you, 

* [Compatibility Table](https://support.system76.com/articles/windows/#compatibility-table)
* [docs/windows.md at master · system76/docs · GitHub](https://github.com/system76/docs/blob/master/content/windows.md)

**Comment by ahoneybun** [comment]
We haven't testing Windows 10 or 11 on the kudu6 at this time and I don't know if that is on the roadmap at this time.

**Comment by juvtib** [comment]
Thank you. If you don't need this issue as a placeholder then please close it
at your convenience. 

Regards,
Mike
