### ISSUE TITLE
software-triage log details update

### ISSUE THREAD

**Issue by garnerlogan65** [system76/docs#934]
This article will need to be updated to reflect the new System76-support panel in Pop_OS! as the driver application is being phased out.

-update log section
-sometimes users are confused on how to send them to us, clarify that we need to be sent these in a ticket response?
-additionally, we will need to delineate whether the driver application is still needed on other distributions, such as Ubuntu.

**Comment by garnerlogan65** [comment]
Update fix package manager commands to tee output to file.

**Comment by ahoneybun** [comment]
Being done with this issue: https://github.com/system76/docs/issues/939
