### ISSUE TITLE
log-files update content

### ISSUE THREAD

**Issue by garnerlogan65** [system76/docs#936]
Update log genration article to reflect the changes of the new support panel. Add upower manual log command.

`upower -d > ~/system76/upower.log`

**Comment by garnerlogan65** [comment]
Change email address from careteam to help

**Comment by garnerlogan65** [comment]
Once arrticle is updated, revise freezing-behavior.md, with latest information to reflect support panel

**Comment by ahoneybun** [comment]
Fixed.
