### ISSUE TITLE
VirtualBox docs do not mention UEFI

### ISSUE THREAD

**Issue by pwyoung** [system76/docs#949]
I tried installing PopOS 21.10 via Vagrant on a Macbook. This failed at the step where it attempts to install the Grub Bootloader. This only seems to work if I change the system in VirtualBox to use UEFI. I suggest updating the docs to tell folks that this is a requirement (if it is) or that they likely need to use UEFI if they see failures like the one I mentioned.

The page I'm referring to is here: 
https://support.system76.com/articles/install-in-vm/

Apparently the source/markup file for this is here:
docs/content/install-in-vm.md

**Comment by pwyoung** [comment]
Right, I have been using PopOS for many years now. I've purchased three
System76 machines, and installed PopOS on a few others, some with UEFI, and
one that was older without it. I have seen PopOS run well on bare-metal
with no problem even on older machines without UEFI.
That's why I was surprised when it failed (3x).

Yes, the error occurred with VirtualBox when the EFI option was not
selected. The only change I made to make this work was to "Enable EFI
(special OSes only)"
The target system is a 2019 MacBook Pro running MacOS Big Sur (v11.5.2),
with VirtualBox 6.1.32 installed via HomeBrew.

I normally run on Linux hosts, and I use QEMU there for the much better
load-times and execution speed.
While researching this yesterday, I found that VirtualBox performance on
the Mac is poor compared to QEMU on the mac.
I suspect the problem with VB is similar to the problem with libvirt on Mac
(not using the Hypervisor framework).

In case it helps you or anyone else, I've attached a script that I am using
to create a PopOS VM that runs much faster than VirtualBox does.

**Comment by jacobgkau** [comment]
> In case it helps you or anyone else, I've attached a script that I am using
> to create a PopOS VM that runs much faster than VirtualBox does.

There was no attachment, and it looks like you replied via e-mail. You'll need to attach files via the GitHub web interface if you want to attach anything.

I was able to recreate this on a Windows 10 host, but not a Pop!_OS host.

**Comment by pwyoung** [comment]
Thanks for the info and corrections. Yes, I did reply by email. That was a mistake.

It's interesting that you can reproduce it on Windows-10.
This happened to me on a Mac-book.

In any case, I thought this info might help someone else.
Thanks for the follow ups!

**Comment by pwyoung** [comment]
[run-popos-on-mac.sh.txt](https://github.com/system76/docs/files/8290509/run-popos-on-mac.sh.txt)

Attached the script I'm using to run PopOs on a Mac via Qemu since it is much faster than VirtualBox.
