### ISSUE TITLE
Where does System76 stand with respect to Btrfs backup/rollback features?

### ISSUE THREAD

**Issue by why-not-try-calmer** [system76/docs#967]
Hello there,

I have been helping and supporting users on [this Telegram group](https://t.me/PopOs_en) and [this Matrix chat](https://matrix.to/#/#pop_os:matrix.org) -- handle: @ad_himself -- for a couple of months and I have been struck by how many people were running into issues that can be averted with simple backup methods. In particular, some of these users looked like they could benefit from the backup/rollback features of _Btrfs_.

Now even though there is already an abundance of material on backing up Pop!_OS using tools and techniques available to _ext4_, there is little on how to take advantage of these tools -- or their relevant counterparts -- on _Btrfs_. Thus, before I get working on landing a PR to fix the situation, I'd like to know where you folks stand -- and where system76 stands -- with respect to _Btrfs_ in relation to backing up and rolling back. In particular, is _Btrfs_ something you expect to see used more on Pop!_OS? And do you agree that it would make sense to better support users interested in taking advantage of its backup / rollback features?

If so there would be two aspects of the question in need of better documentation coverage:
1. How to install Pop! with a _Btrfs_ layout?
2. How to take advantage of its backup / rollback features?

(1) is pretty much covered in [this guide](https://github.com/spxak1/weywot/blob/main/Pop_Btrfs_Subvolumes_with_Timeshift.md). I think I could get the other author to adapt it to this documentation, but this would presuppose that you / system76 looks favourably at _Btrfs_ as a genuinely / officially supported file-system. This is something I'd like to hear you on.

As for (2) there is of course Timeshift, already discussed in this documentation, but there are alternatives or complement worth mentioning (btrbk, and others). Moreover, documenting these tools require I think some background information about "back up strategies" -- for instance it might not be obvious to new users that they in fact would need to draw a sharp distinction between backing up their file systems and backing up their user files / documents, so that's also a topic to discuss within this broader issue.

**Comment by why-not-try-calmer** [comment]
Okay, that's a great news. I'll get to work then

**Comment by bettyvschmartz** [comment]
Some great guides [here](https://mutschler.eu/linux/install-guides/) with BTRFS, BTRBK | Timeshift, and auto-apt snapshots. Includes sending BTRFS backups to an encrypted backup disk. 

-- bvs

**Comment by why-not-try-calmer** [comment]
Thanks. Can anyone confirm that the default volumes layout will match Ubuntu's, namely @ for / (root) and @home for /home?
