### ISSUE TITLE
Steam not Opening on Pop!_OS 20.04 LTS with nvidia 510 drivers

### ISSUE THREAD

**Issue by amitsandhel** [system76/docs#978]
Hello 
I am trying to follow your docs and attempting to install Steam on my PopOs machine from the PopOS shop. When I attempt to open steam it does not open at all. It just clicks and does nothing. I did two restart of my laptop as well but no changes happened. 
By any chance is the new nvidia 510 driver incompatible with Steam ?

https://support.system76.com/articles/linux-gaming/

This is the operating system I have:
**Operating system:** Pop!_OS 20.04 LTS
**nvidia driver:** nvidia-driver-510 specifically 510.54 
**nvidia graphic cards**: NVIDIA Corporation GP107M [GeForce GTX 1050 Ti Mobile] / NVIDIA GeForce GTX

If I attempt to install Steam using the terminal it gives me this output:
steam:i386 is already the newest version (1:1.0.0.74-1pop1~1644936575~20.04~6d77918).

Conversely running Steam from the terminal gives me this output
$ steam
steam.sh[5216]: Running Steam on pop 20.04 64-bit
steam.sh[5216]: STEAM_RUNTIME is enabled automatically
setup.sh[5287]: Steam runtime environment up-to-date!
steam.sh[5216]: Steam client's requirements are satisfied

The version of Steam I installed is from the proton store the deb version. I also installed the Steam Installer as well which is the ubuntu(deb)

I have yet to install protonup since I can't even open Steam so I wanted some direction before I continued with the installation process 
Snapshot of the Steam libraries I installed
![Screenshot from 2022-03-30 00-02-56](https://user-images.githubusercontent.com/8258474/160749827-fdf397ea-17eb-4c6f-a438-5fceecb844e1.png)

Thank you for your time and consideration, I look forward to hearing back from you. 

Best,
Amit

**Comment by Ampersandstorm** [comment]
Hi Amit, sorry to hear of these continued issues launching Steam. This repo is for reporting issues or suggesting improvements to the support.system76.com documentation. If this is an issue strictly related to Pop!_OS, I would suggest posting this over at https://github.com/pop-os/pop/issues
