### ISSUE TITLE
NVIDIA based eGPU requires well timed unplug during boot to load driver

### ISSUE THREAD

**Issue by compiaffe** [system76/docs#98]
I have a AORUS GTX 1080 Gaming Box eGPU which attaches via Thunderbolt 3 to my Galago Pro with PopOS 18.04 and NVIDIA drivers.

In order to have the GPU driver available (as in show up with `nvidia-smi`) I have to plug in the device before boot and pull it out just after the hdd encryption password. Otherwise the laptop will be stuck and the PopOS login screen does not appear.
Once plugged out the login screen loads, I replug the camera, wait until the drivers have loaded (by waiting until the fancy LED lights on the eGPU turn on) and log into PopOS. 
Then `nvidia-smi` works however and I can use the GPU in nvidia-docker successfully. 
I am not sure if PopOS actually uses the GPU for rendering software though.

I can plug an external monitor into the graphics card and the monitor recognises being plugged in, but nothing is shown on the monitor. Keeping the monitor directly plugged into the laptop still works though.
Switching between the two is tricky and often requires a hard reset.

How can I 
(a) get PopOS to launch without the need to replug the GPU during boot
(b) make sure PopOS uses the GPU for rendering software
(c) be able to plug in the GPU after PopOS is loaded

Thank you

**Comment by ahoneybun** [comment]
This is the documentation for system76's support site support.system76.com and not a support spot. Your best place would be our Pop mattermost here: chat.pop-os.org
