### ISSUE TITLE
Links to Pop Planet should be removed from difference-between-pop-ubuntu.md

### ISSUE THREAD

**Issue by Ampersandstorm** [system76/docs#996]
"For an in-depth look at the effort and manpower that goes into updating and maintaining Pop!_OS, take a look at our [Roadmap](https://support.system76.com/articles/roadmap) documentation and the [This Week in Pop!](https://pop-planet.info/forums/forums/project-updates.28/) series on [Pop!_Planet](https://pop-planet.info/). 

- Leads to 404 page, appears the site is no longer active. I believe https://blog.system76.com/ now serves a similar purpose.

**Comment by jacobgkau** [comment]
Sad that Pop!_Planet is offline (that must have happened recently), but I know "This Week in Pop!" had not been updated in at least a couple of years anyway.
